<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View\Details;
use Magento\Framework\Escaper;

/** @var Details $block */
/** @var Escaper $escaper */

$titleRenderer = $block->getChildBlock('product.section.title.renderer');
$defaultTitleTemplate = $titleRenderer->getTemplate();

?>
<div class="grid lg:grid-cols-2 gap-8">
    <?php foreach ($block->getGroupSortedChildNames('detailed_info', '') as $sectionName): ?>
        <?php
            $sectionBlock  = $block->getLayout()->getBlock($sectionName);
            $sectionHtml   = (string) $sectionBlock->toHtml();
            $titleTemplate = $sectionBlock->getData('title_template') ?? $defaultTitleTemplate;

            if (empty(trim($sectionHtml))) {
                continue;
            }
        ?>

        <section id="<?= $escaper->escapeHtmlAttr($sectionBlock->getNameInLayout()) ?>">
            <?=
                $titleRenderer->setTemplate($titleTemplate)
                            ->assign('sectionBlock', $sectionBlock)
                            ->toHtml()
            ?>
            <?= /** @noEscape  */ $sectionHtml ?>
        </section>
    <?php endforeach; ?>
</div>
