<?php

use Magento\Framework\Escaper;
use Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer;
use Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Attribute;

/** @var FilterRenderer $block */
/** @var Attribute $this */
/** @var Escaper $escaper */

$uniqueId = '_' . uniqid();
$jsLayout = $this->getJsLayout();
$datascope = $this->getFilter()->getRequestVar() . 'Filter';
$filterName = $this->getFilter()->getName();
?>

<?php if (!empty($filterItems)) : ?>
    <?= $block->getChildBlock('attribute-filter-js')
        ->setUniqueId($uniqueId)
        ->setJsLayout($jsLayout)
        ->setScope($datascope)
        ->toHtml() ?>

    <div
        class="<?= $escaper->escapeHtml($datascope); ?>"
        x-data="initSmileAttibute<?= $uniqueId ?>()"
        x-init="initialize();"
    >
        <div class="field search"  x-show="displaySearch">
            <div class="control">
                <input
                    class="filter-search w-full mb-2 rounded-lg border-slate-300 bg-slate-50"
                    type="text"
                    aria-label="<?= $escaper->escapeHtmlAttr( __('Search %1 filter', $filterName)) ?>"
                    autocomplete="off"
                    :placeholder="searchPlaceholder"
                    @keyup="onSearchChange"
                    @focusout="onSearchFocusOut"
                >
            </div>
        </div>
        <ol
            class="items space-y-2.5 my-2 outline-offset-4"
            aria-label="<?= $escaper->escapeHtmlAttr(__('%1 filter options', $filterName)) ?>"
            tabindex="-1"
            x-ref="closestItems<?= $uniqueId ?>"
        >
            <template x-for="attribute in displayedItems">
                <li class="item relative text-sm">
                    <a
                        class="group/filter flex gap-2 justify-between items-center hover:text-black outline-offset-4"
                        :href="attribute.url"
                        x-show="attribute.count >= 1"
                        :rel="options.displayRelNofollow"
                    >
                        <span class="flex gap-2 items-center">
                            <svg
                                fill="none"
                                class="rounded-sm border border-slate-300 bg-white text-white transition
                                    group-hover/filter:bg-primary group-hover/filter:border-primary group-focus/filter:bg-primary group-focus/filter:border-primary"
                                :class="attribute.is_selected ? 'bg-primary border-primary' : 'border-slate-300 bg-white'"
                                width="20"
                                height="20"
                                viewBox="0 0 24 24"
                                xmlns="http://www.w3.org/2000/svg"
                                aria-hidden="true"
                                stroke-width="2"
                                stroke="currentColor"
                            >
                                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5"></path>
                            </svg>
                            <span x-html="attribute.label"></span>
                        </span>
                        <div class="ml-2">
                            <span class="count text-slate-500 tabular-nums" :class="!options.displayProductCount && 'sr-only'">
                                <span x-text="attribute.count"></span><span class="sr-only"><?= $escaper->escapeHtml(__('products available')) ?></span>
                            </span>
                            <template x-if="attribute.is_selected">
                                <span class="sr-only"><?= $escaper->escapeHtml(__('filter selected')) ?></span>
                            </template>
                        </div>
                    </a>
                    <div x-show="attribute.count < 1">
                        <span x-html="attribute.label"></span>
                        <span class="count text-slate-500 tabular-nums" x-text="attribute.count"></span>
                    </div>
                </li>
            </template>
        </ol>

        <div class="no-results-message" x-model="result" x-show="getFulltextSearch() && !hasSearchResult()" class="empty">
            <p x-html="getSearchResultMessage()"></p>
        </div>

        <div class="actions mt-4" x-show="enableExpansion()">
            <button
                class="show-more btn text-sm w-full py-2 px-3 shadow-none justify-center bg-slate-100 text-current hover:shadow-none hover:bg-slate-200 focus:bg-slate-200"
                @click="onShowMore(); $refs.closestItems<?= $uniqueId ?>.focus()"
                x-show="displayShowMore()"
                x-text="showMoreLabel"
            ></button>
            <button
                class="show-less btn text-sm w-full py-2 px-3 shadow-none justify-center bg-slate-100 text-current hover:shadow-none hover:bg-slate-200 focus:bg-slate-200"
                @click="onShowLess(); $refs.closestItems<?= $uniqueId ?>.focus()"
                x-show="displayShowLess()"
                x-text="showLessLabel"
            ></button>
        </div>
    </div>
<?php endif; ?>
