<?php

use Magento\Framework\Escaper;
use Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Slider;

/** @var Slider $block */
/** @var Escaper $escaper */

$uniqueId = '_' . uniqid();
$jsConfig = $this->getJsonConfig();
$dataRole = $block->getDataRole();
$childBlockName = (strpos($dataRole, 'price') !== false) ? 'renderer.price.slider' : 'renderer.slider' ;
$filterTitle = 'price';
?>

<?= $block->getChildBlock($childBlockName)
    ->setUniqueId($uniqueId)
    ->setJsConfig($jsConfig)
    ->setDataRole($dataRole)
    ->toHtml() ?>

<div class="smile-es-range-slider" data-role="<?= $block->getDataRole(); ?>">
    <div x-data="rangeSlider<?= $uniqueId ?>()" x-init="initialize()" class="relative max-w-xl w-full">
        <div x-html="message" class="mb-2 text-sm text-slate-700">&ZeroWidthSpace;</div>
        <div
            class="es-range-slider multirange-slider relative rounded-md bg-gray-200"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Range slider')) ?>"
            aria-describedby="range-handler"
            :style="`--tw-range-fill-min: ${minthumb}; --tw-range-fill-max: ${maxthumb}`"
        >
            <label
                for="<?= $escaper->escapeHtmlAttr($uniqueId) ?>-min-price"
                class="sr-only"
            ><?= $escaper->escapeHtml(__('Minimal %1', $filterTitle)) ?></label>
            <input
                id="<?= $escaper->escapeHtmlAttr($uniqueId) ?>-min-price"
                type="range"
                step="1"
                :min="min"
                :max="max"
                @input="mintrigger"
                x-model="minprice"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Minimum price value, use left and right arrows to adjust.')) ?>"
                :aria-valuetext="`${minprice}-${maxprice}`"
            >
            <label
                for="<?= $escaper->escapeHtmlAttr($uniqueId) ?>-max-price"
                class="sr-only"
            ><?= $escaper->escapeHtml(__('Maximum %1', $filterTitle)) ?></label>
            <input
                id="<?= $escaper->escapeHtmlAttr($uniqueId) ?>-max-price"
                type="range"
                step="1"
                :min="min"
                :max="max"
                @input="maxtrigger"
                x-model="maxprice"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Maximum price value, use left and right arrows to adjust.')) ?>"
                :aria-valuetext="`${minprice}-${maxprice}`"
            >
            <div class="z-10 top-0 bottom-0 rounded-md bg-primary" x-bind:style="'right:'+ (100 - 1 - maxthumb)+'%; left:'+ minthumb+'%'"></div>
        </div>
        <div class="flex justify-between items-center py-4 gap-6" aria-hidden="true">
            <input
                type="number"
                step="1"
                :min="min"
                :max="max"
                @input="mintrigger"
                x-model="minprice"
                class="w-full flex-auto rounded-lg border-slate-300 bg-slate-50"
                tabindex="-1"
            >
            <span class="text-sm"><?= $escaper->escapeHtml(__('to')) ?></span>
            <input
                type="number"
                step="1"
                :min="min"
                :max="max"
                @input="maxtrigger"
                x-model="maxprice"
                class="w-full flex-auto rounded-lg border-slate-300 bg-slate-50"
                tabindex="-1"
            >
        </div>
        <a
            class="btn btn-primary btn-size-sm"
            x-model="url"
            :href="url"
            :aria-label="
                hyva.str('<?= $escaper->escapeJs(__('Apply pricing filtering, minimum price %1, maximum price %2')) ?>', minprice, maxprice) + ', ' +
                hyva.str('<?= $escaper->escapeJs(__('%1 products available')) ?>', count)
            "
        >
            <span><?= $escaper->escapeHtml(__('Apply Filter')) ?></span>
        </a>
    </div>
</div>


