<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Review\Block\Product\View as ProductReview;
use Magento\Framework\Escaper;

/** @var ProductReview $block */
/** @var Escaper $escaper */
?>

<div class="grid grid-cols-1 gap-8 md:grid-cols-2">
    <?= $block->getChildHtml('') ?>
</div>
