<div class="mt-24 p-6 bg-[#E2E8F0] rounded-xl lg:flex lg:gap-10">

    <div class="flex justify-center -mt-24 lg:mt-0">
        <div class="rounded-full overflow-hidden w-36 h-36 lg:w-56 lg:h-56">
            <img
                alt="Laura Peterson"
                src="https://unsplash.com/photos/6mRfNloPHlc/download?force=true&auto=format&fit=crop&w=240&q=80"
                width="240"
                height="258"
                loading="lazy"
            >
        </div>
    </div>

    <div class="mt-6 text-center lg:text-left ">
        <div class="relative">
            <div class="text-[#CBD5E1] text-9xl font-bold absolute left-0 -top-8 lg:-ml-6">
                “
            </div>
            <div class="relative text-gray-800 text-2xl font-medium max-w-4xl lg:pl- xl:text-3xl">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu neque aliquam metus porta
                sagittis. Nunc velit ligula, vestibulum et neque et, ullamcorper convallis.
            </div>
        </div>
        <div class="text-blue-600 text-lg leading-7 font-bold mt-4">
            Laura Peterson
        </div>
        <div class="text-[#94A3B8] leading-6">
            Awesome Company
        </div>
    </div>

</div>
