<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Footer;
use Magento\Framework\Escaper;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<small class="text-sm text-slate-700">
    © 2023 Hyva Themes B.V.
    <?php /* Enable the following line to show the copyright information configured in the admin
    <span><?= $escaper->escapeHtml($block->getCopyright()) ?></span>
    */ ?>
</small>
