<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<nav aria-label="<?= $escaper->escapeUrl($escaper->escapeHtmlAttr('Company')) ?>">
    <ul>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('about-us')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('About us')) ?></a>
        </li>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Blog')) ?></a>
        </li>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Our stores')) ?></a>
        </li>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Sustainability')) ?></a>
        </li>
    </ul>
</nav>
