<div class="relative flex flex-col text-center px-14 gap-8">
    <div class="text-blue-100 text-9xl font-bold absolute left-0 -top-8">
        “
    </div>
    <div class="flex-1 text-gray-800 text-2xl leading-8 font-medium">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu neque aliquam metus porta sagittis.
        Nunc velit ligula, vestibulum et neque et, ullamcorper convallis.
    </div>
    <div class="flex justify-center gap-4 items-center">
        <div class="rounded-full overflow-hidden w-28 h-28">
            <img
                alt="Laura Peterson"
                src="https://unsplash.com/photos/6mRfNloPHlc/download?force=true&auto=format&fit=crop&w=120&q=80"
                width="120"
                height="129"
                loading="lazy"
            >
        </div>
        <div>
            <div class="text-gray-600 text-lg leading-7 font-bold">
                Laura Peterson
            </div>
            <div class="text-blue-300 leading-6 mt-1">
                Awesome Company
            </div>
        </div>
    </div>
</div>
