<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\LocaleFormatter;
use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
/** @var LocaleFormatter $localeFormatter */

$firstNum = $localeFormatter->formatNumber($block->getFirstNum());
$lastNum = $localeFormatter->formatNumber($block->getLastNum());
$totalNum = $localeFormatter->formatNumber($block->getTotalNum());

?>
<p class="toolbar-amount text-sm text-slate-800 text-balance">
    <?php if ($block->getLastPageNum() > 1): ?>
        <?= $escaper->escapeHtml(__('Items %1 to %2 of %3', $firstNum, $lastNum, $totalNum)) ?>
    <?php elseif ($block->getTotalNum() == 1): ?>
        <?= $escaper->escapeHtml(__('%1 Item', $totalNum)) ?>
    <?php else: ?>
        <?= $escaper->escapeHtml(__('%1 Item(s)', $totalNum)) ?>
    <?php endif; ?>
</p>
