<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Block\SortableItem;
use Magento\Framework\Escaper;

/** @var SortableItem $block */
/** @var Escaper $escaper */

$label = $block->getLabel();
$path = $block->getPath();
?>

<?php if ($label && $path): ?>
    <a
        class="block py-1.5 hover:underline"
        href="<?= $escaper->escapeUrl($block->getUrl($path)) ?>"
    ><?= $escaper->escapeHtml($label) ?></a>
<?php endif; ?>
