<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="pt-2 pb-4 px-6">
    <a
        href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
        class="btn btn-primary"
    >
        <?= $heroicons->shoppingCartHtml('shrink-0', 20, 20, ['aria-hidden' => 'true']); ?>
        <?= $escaper->escapeHtml(__('Shopping Cart')) ?>
    </a>
</div>
