<article class="max-w-full prose prose-slate prose-li:my-0 prose-p:my-8 prose-lead:mt-0 md:prose-h1:text-5xl">
    <div class="mb-12 space-y-8">
        <span class="inline-block px-2 py-1 rounded bg-blue-100 text-blue-600 text-lg leading-7 font-semibold uppercase lg:text-xl">About us</span>
        <h1>Everything you need to know</h1>
    </div>
    <div class="md:columns-2 md:gap-x-8">
        <p class="lead text-lg font-medium">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu neque aliquam metus porta
            sagittis. Nunc velit ligula, vestibulum et neque et, ullamcorper convallis lacus. Donec a neque
            iaculis, dictum nisl ut, dictum nisi. Praesent sagittis augue ac pulvinar lobortis. Quisque
            molestie velit metus, eu ultricies ligula accumsan tempus.
        </p>
        <p>
            Aliquam non enim in nulla pellentesque rhoncus. Aenean faucibus ligula quam, eu iaculis erat rhoncus
            vel. Maecenas non est et nisi accumsan faucibus vitae sit amet sapien. Maecenas euismod, urna vitae
            elementum congue, nulla diam semper odio, ac vehicula nisl quam eu nibh. Quisque lacinia orci mi,
            ac auctor mi mattis vel. Mauris aliquet nisi a pulvinar varius. Curabitur luctus dolor ac nibh rutrum
            lacinia. Curabitur vestibulum commodo lectus eget dictum. Etiam at sagittis lacus. Pellentesque mattis
            leo non odio vestibulum ultrices. Duis at tellus tellus.
        </p>
        <blockquote class="flex gap-3 items-start border-l-0 my-10 pl-0 text-2xl font-normal not-italic text-slate-800
            before:content-[open-quote] before:-mt-2 before:text-blue-100 before:text-8xl before:leading-none before:font-bold">
            Nullam nec tortor semper, mattis tortor ut, dictum augue. Etiam vitae tellus turpis. Aenean dictum
            metus non turpis luctus, ut egestas mi facilisis.
        </blockquote>
        <p>
            Quisque accumsan congue ex in placerat. Donec ac pellentesque sapien, id ullamcorper nulla. Vestibulum
            tempus aliquam luctus. Nullam malesuada suscipit finibus. Sed posuere venenatis nisl, et vestibulum
            massa cursus vitae. Vivamus eu tempus mauris. Aliquam viverra mauris quam, maximus placerat arcu
            tristique sed. Nam at tincidunt lorem.
        </p>
        <figure>
            <img
                src="https://unsplash.com/photos/9HI8UJMSdZA/download?force=true&auto=format&fit=crop&w=728&q=80"
                alt="Relay runner"
                width="728"
                height="485"
                loading="lazy"
                class="rounded-2xl"
            >
            <figcaption class="text-blue-600 mt-4">Proin quis odio feugiat, sodales lectus vel, commodo ipsum.</figcaption>
        </figure>
        <p>
            Morbi in lectus at eros luctus mollis. Vivamus lobortis urna in quam dignissim tempus. Sed volutpat
            ipsum vitae justo sagittis venenatis. Vestibulum eros elit, scelerisque eget velit a, viverra eleifend
            augue. Integer in ante non felis ornare tempus. Nam ut mi id lorem maximus ornare sit amet vitae enim.
        </p>
        <ul class="marker:text-blue-700">
            <li>Proin dictum sodales velit at finibus.</li>
            <li>Donec id cursus ante.</li>
            <li>Interdum et malesuada fames ac ante.</li>
            <li>Nam malesuada maximus ultricies.</li>
        </ul>
    </div>
</article>
