<div class="p-6 leading-6 text-gray-500">

    <div class="flex flex-col items-center gap-2">
        <span class="uppercase bg-blue-100 rounded px-2 py-1 text-blue-600 text-lg leading-7 font-semibold md:text-xl">
            Why Hyvä?
        </span>
        <div class="text-4xl leading-10 font-bold text-gray-800 md:text-5xl">
            Here’s why.
        </div>
    </div>

    <div class="mt-8 grid gap-6 md:grid-cols-2">

        <div class="flex gap-4">
            <div>
                <div class="w-16 h-16 bg-blue-200 text-blue-800 rounded-full flex justify-center items-center">
                    {{icon "heroicons/solid/shield-check" classes="w-12 h-12 fill-current" width=48 height=48}}
                </div>
            </div>
            <div>
                <div class="text-lg text-gray-800 font-medium leading-7 mb-2">
                    Safe and secure
                </div>
                <div>
                    Sed posuere venenatis nisl, et vestibulum massa cursus vitae. Vivamus eu tempus mauris. Aliquam
                    viverra mauris quam, maximus placerat arcu tristique sed. Nam at tincidunt lorem.
                </div>
            </div>
        </div>

        <div class="flex gap-4">
            <div>
                <div class="w-16 h-16 bg-blue-200 text-blue-800 rounded-full flex justify-center items-center">
                    {{icon "heroicons/solid/truck" classes="w-12 h-12 fill-current" width=48 height=48}}
                </div>
            </div>
            <div>
                <div class="text-lg text-gray-800 font-medium leading-7 mb-2">
                    Free shipping
                </div>
                <div>
                    Aliquam erat volutpat. Cras venenatis ullamcorper metus at vulputate. Pellentesque habitant morbi
                    tristique senectus et netus et malesuada fames ac turpis egestas.
                </div>
            </div>
        </div>

        <div class="flex gap-4">
            <div>
                <div class="w-16 h-16 bg-blue-200 text-blue-800 rounded-full flex justify-center items-center">
                    {{icon "heroicons/solid/gift" classes="w-12 h-12 fill-current" width=48 height=48}}
                </div>
            </div>
            <div>
                <div class="text-lg text-gray-800 font-medium leading-7 mb-2">
                    Amazing gift-wrapping
                </div>
                <div>
                    Integer in ante non felis ornare tempus. Nam ut mi id lorem maximus ornare sit amet vitae enim.
                    Nam a dictum sapien. Proin dictum sodales velit at finibus.
                </div>
            </div>
        </div>

        <div class="flex gap-4">
            <div>
                <div class="w-16 h-16 bg-blue-200 text-blue-800 rounded-full flex justify-center items-center">
                    {{icon "heroicons/solid/receipt-tax" classes="w-12 h-12 fill-current" width=48 height=48}}
                </div>
            </div>
            <div>
                <div class="text-lg text-gray-800 font-medium leading-7 mb-2">
                    The best deals
                </div>
                <div>
                    Donec id cursus ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam malesuada
                    maximus ultricies. Etiam vel lectus sit amet dui viverra pretium.
                </div>
            </div>
        </div>

    </div>
</div>
