<!--
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
-->

<div class="py-3 px-6 bg-gray-100 divide-y">
    <details
        class="group details-animate"
        name="accordion_67f7a7083a107"
        open
    >
        <summary class="flex [&::-webkit-details-marker]:hidden w-full items-center justify-between py-3 font-bold cursor-pointer">
            <span class="flex items-center gap-2">Question 1</span>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="20" height="20" aria-hidden="true" class="transition-transform group-open:rotate-180">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
        </summary>
        <div class="flow-root pb-3">Lorem ipsum dolor sit, amet consectetur adipisicing elit. </div>
    </details>

    <details
        class="group details-animate"
        name="accordion_67f7a7083a107"
    >
        <summary class="flex [&::-webkit-details-marker]:hidden w-full items-center justify-between py-3 font-bold cursor-pointer">
            <span class="flex items-center gap-2">Question 2</span>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="20" height="20" aria-hidden="true" class="transition-transform group-open:rotate-180">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
        </summary>
        <div class="flow-root pb-3">
            <div class="prose">
                <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit.</p>
                <p>Iusto itaque voluptatibus iste minima libero harum repellat!</p>
            </div>
        </div>
    </details>
</div>
