<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Checkout\Block\Onepage\Success;
use Magento\Framework\Escaper;

/** @var Success $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()): ?>
    <a
        href="<?= $escaper->escapeUrl($block->getPrintUrl()) ?>"
        class="mt-4 md:mt-0 md:ml-auto btn inline-flex gap-2 p-2"
        title="<?= $escaper->escapeHtml(__('Print receipt')) ?>"
        target="_blank"
        rel="noopener"
    >
        <?= $heroicons->printerHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
        <span class="md:sr-only"><?= $escaper->escapeHtml(__('Print receipt')) ?></span>
    </a>
    <?= $block->getChildHtml() ?>
<?php endif;?>
