<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Checkout\Block\Onepage\Success;

/** @var ViewModelRegistry $viewModels */
/** @var Success $block */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$iconSize = 48;
?>

<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getCanViewOrder()): ?>
            <p>
                <?= $escaper->escapeHtml(__(
                    'Your order number is: %1.',
                    sprintf(
                        '<a href="%s" class="underline">%s</a>',
                        $escaper->escapeUrl($block->getViewOrderUrl()),
                        $block->getOrderId()
                    )
                ), ['a']) ?>
            </p>
        <?php  else: ?>
            <p><?= $escaper->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
        <p>
            <?= $escaper->escapeHtml(
                __('We\'ll email you an order confirmation with details and tracking info.')
            ) ?>
        </p>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="mt-6">
        <a
            class="inline-flex w-full sm:w-auto btn btn-primary"
            href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>"
        ><?= $escaper->escapeHtml(__('Continue Shopping')) ?></a>
    </div>
</div>
