<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\View\Gallery;
use Magento\Catalog\Helper\Image;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Gallery $block */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, [$block, 'isMainImage']));

if (!empty($images) && empty($mainImage)) {
    $mainImage = reset($images);
}

/** @var Image $helper */
$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$smallWidth = $block->getImageAttribute('product_page_image_small', 'width', 90);
$smallHeight = $block->getImageAttribute('product_page_image_small', 'height', 90);
$mediumWidth = $block->getImageAttribute('product_page_image_medium', 'width', 700);
$mediumHeight = $block->getImageAttribute('product_page_image_medium', 'height', 700);

// Admin Config
$galleryOptionShowRelated = $storeConfig->getStoreConfig('catalog/product_video/show_related') ?? false;
$galleryOptionVideoLoop = $storeConfig->getStoreConfig('catalog/product_video/video_auto_restart') ?? false;

// view.xml Config
$galleryOptionNavVertical = (string) $block->getVar('gallery/navdir', 'Magento_Catalog') === 'vertical';
$galleryOptionAllowfullscreen = (bool) $block->getVar('gallery/allowfullscreen', 'Magento_Catalog');
$galleryOptionLoop = (bool) $block->getVar('gallery/loop', 'Magento_Catalog');
$galleryOptionArrows = $block->getVar('gallery/arrows', 'Magento_Catalog');
$galleryOptionShowCaption = (bool) $block->getVar('gallery/caption', 'Magento_Catalog');
$galleryOptionShowDots = (string) $block->getVar('gallery/nav', 'Magento_Catalog') === 'dots';
$galleryOptionShowFullscreenIcon = (bool) $block->getVar('gallery/fullscreenicon', 'Magento_Catalog');
$galleryOptionVideoAutoplay = (bool) $block->getVar('gallery/autoplay', 'Magento_Catalog');
$galleryOptionAppendOnReceive = (string) $block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct') === 'append';

$productName = $block->getProduct()->getName();
?>

<div
    class="w-full pt-6 md:pt-0 md:h-auto md:row-start-1 md:row-span-2 md:col-start-1"
    style="
        --gallery-ratio: <?= /* @noEscape */ $mediumWidth . '/' . $mediumHeight ?>;
        --gallery-width: <?= /* @noEscape */ $mediumWidth ?>px;
    "
>
    <section
        id="gallery"
        aria-label="<?= $escaper->escapeHtmlAttr(__('%1 Gallery', $productName)) ?>"
        x-data="initGallery"
        x-bind="eventListeners"
        class="splide max-w-full h-full w-[var(--gallery-width)]"
    >
        <data itemprop="image" value="<?= /* @noEscape */ $mainImageData ?>">
        <div class="relative">
            <div
                class="max-w-full w-[var(--gallery-width)] aspect-[var(--gallery-ratio)]"
                aria-hidden="true"
                x-show="fullscreen"
            ></div>
            <div
                class="z-50 backdrop"
                aria-hidden="true"
                x-show="fullscreen"
                x-transition.opacity
                @click="closeFullscreen"
            ></div>
            <div
                class="group relative grid bg-container-darker rounded-lg overflow-hidden aspect-[var(--gallery-ratio)]
                    data-[fullscreen=true]:z-50 data-[fullscreen=true]:fixed data-[fullscreen=true]:inset-0 data-[fullscreen=true]:w-screen
                    data-[fullscreen=true]:max-w-[min(1280px,(100%_-_2rem))] data-[fullscreen=true]:max-h-[min(1024px,(100%_-_2rem))]
                    data-[fullscreen=true]:m-auto lg:data-[fullscreen=true]:aspect-auto"
                :data-fullscreen="fullscreen"
                aria-live="polite"
                aria-atomic="true"
                x-ref="galleryDialog"
                :role="fullscreenRole"
                :aria-modal="fullscreen"
                :aria-label="fullscreenLabel"
            >
                <div class="splide__track">
                    <ul class="splide__list">
                        <template x-for="(image, index) in images" :key="index">
                            <li class="splide__slide">
                                <figure class="flex flex-col w-full h-full">
                                    <template x-if="isActiveVideo">
                                        <iframe
                                            class="absolute inset-0 aspect-video max-w-full max-h-full h-auto m-auto"
                                            width="1280"
                                            height="720"
                                            type="text/html"
                                            frameborder="0"
                                            loading="lazy"
                                            x-data="getVideoData"
                                            :src="src"
                                            :alt="setImageCaption"
                                            :title="setImageCaption"
                                            :allow="allow"
                                        ></iframe>
                                    </template>
                                    <img
                                        width="<?= /* @noEscape */ $mediumWidth ?>"
                                        height="<?= /* @noEscape */ $mediumHeight ?>"
                                        class="max-w-full max-h-full m-auto object-contain
                                            group-data-[fullscreen=true]:w-auto"
                                        :src="setImage"
                                        :alt="setImageCaption"
                                        x-show="notActiveVideo"
                                    >
                                    <?php if ($galleryOptionShowCaption): ?>
                                        <template x-if="showCaption">
                                            <figcaption
                                                class="absolute inset-x-0 bottom-0 pt-4 pb-2 px-4 text-sm xl:text-base font-bold bg-gradient-to-t from-black/10
                                                    <?= $galleryOptionArrows !== "start" && $galleryOptionArrows !== "end" ? 'text-center' : 'text-left' ?>
                                                    <?= $galleryOptionArrows === "start" ? 'text-right' : '' ?>"
                                                x-text="image.caption"
                                            ></figcaption>
                                        </template>
                                    <?php endif; ?>
                                </figure>
                            </li>
                        </template>
                    </ul>
                </div>
                <?php if ($galleryOptionAllowfullscreen): ?>
                    <button
                        class="absolute inset-0 w-full -outline-offset-2"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Open fullscreen')) ?>"
                        x-show="canShowFullscreenToggle"
                        x-cloak
                        @click="openFullscreen"
                    >
                        <?php if ($galleryOptionShowFullscreenIcon): ?>
                            <span
                                title="<?= $escaper->escapeHtmlAttr(__('Open fullscreen')) ?>"
                                class="block absolute top-2 right-2"
                            >
                                <span class="block p-2 rounded-full transition shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary/50 hover:text-primary focus:text-primary">
                                    <?= $heroicons->arrowsExpandHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
                                </span>
                            </span>
                        <?php endif; ?>
                    </button>
                    <button
                        class="z-50 fixed top-2 right-2 lg:top-6 lg:right-6 p-2 rounded-full transition shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary"
                        title="<?= $escaper->escapeHtmlAttr(__('Close fullscreen')) ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Close fullscreen')) ?>"
                        x-show="fullscreen"
                        @click="closeFullscreen"
                    >
                        <?= $heroicons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
                    </button>
                <?php endif; ?>
                <button
                    class="group absolute inset-0 w-full -outline-offset-2 grid place-items-center"
                    title="<?= $escaper->escapeHtmlAttr(__('Click to play video')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Click to play video')) ?>"
                    x-show="canShowActiveVideoToggle"
                    x-cloak
                    @click="openActiveVideo"
                >
                    <?= $heroiconsSolid->playHtml(
                        'stroke-white/75 fill-black/20 transition ease-in group-hover:scale-110 md:w-24 md:h-24',
                        44,
                        44,
                        ['aria-hidden' => 'true']
                    ); ?>
                </button>
                <?php if ($galleryOptionArrows): ?>
                    <div class="splide__arrows z-10 absolute bottom-4 md:bottom-2 lg:bottom-4 xl:bottom-8 flex justify-between gap-2
                        <?= $galleryOptionArrows !== "start" ? 'right-4 md:right-2 lg:right-4 xl:right-8' : '' ?>
                        <?= $galleryOptionArrows !== "end" ? 'left-4 md:left-2 lg:left-4 xl:left-8' : '' ?>"
                    >
                        <button class="splide__arrow splide__arrow--prev shrink-0 p-2.5 rounded-full transition disabled:opacity-30 shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary">
                            <?= $heroiconsSolid->arrowLeftHtml('', 16, 16, ['aria-hidden' => 'true']); ?>
                        </button>
                        <button class="splide__arrow splide__arrow--next shrink-0 p-2.5 rounded-full transition disabled:opacity-30 shadow hover:shadow-primary/30 focus:shadow-primary/30 bg-white text-primary">
                            <?= $heroiconsSolid->arrowRightHtml('', 16, 16, ['aria-hidden' => 'true']); ?>
                        </button>
                    </div>
                <?php endif; ?>
            </div>
            <ul class="splide__pagination p-2 gap-1"></ul>
        </div>
    </section>
    <script>
        function initGallery() {
            return {
                gallery: null,
                activeItem: 0,
                activeVideo: false,
                itemIsVideo: false,
                fullscreen: false,
                isMoving: false,
                videoOptions: {
                    autoplay: <?= $galleryOptionVideoAutoplay ? 'true' : 'false' ?>,
                    loop: <?= $galleryOptionVideoLoop ? 'true' : 'false' ?>,
                    showRelated: <?= $galleryOptionShowRelated ? 'true' : 'false' ?>,
                    allowApi: false
                },
                initialImages: <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                images: <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                init() {
                    this.$nextTick(() => {
                        this.initSlider();
                    });
                    this.$watch('fullscreen', (open) => {
                        // *1: Required to keep the slider in sync
                        this.refreshSlider(); // *1

                        this.$nextTick(() => {
                            this.goToSlide(this.activeItem); // *1
                            this.scrollLock(open);
                            this.tabLock(this.$refs.galleryDialog, open);
                        })
                    })
                },
                initSlider() {
                    const splidePaginationDotClasses = 'splide__pagination__page block rounded-full w-3 h-3 border-2 border-slate-200 transition duration-300 ease-out hover:border-slate-300 hover:bg-slate-300 aria-selected:bg-primary aria-selected:border-primary';

                    // NOTE: Dynamic Alpine Sliders don't play nice with the loop option,
                    // this creates clones of the slides which breaks the images render,
                    // So only use the type options: fade or slide
                    this.gallery = new Splide(this.$root, {
                        type: 'slide',
                        rewind: <?= $galleryOptionLoop ? 'true' : 'false' ?>,
                        perPage: 1,
                        gap: 0,
                        drag: true,
                        keyboard: true,
                        slideFocus: true,
                        arrows: <?= $galleryOptionArrows ? 'true' : 'false' ?>,
                        pagination: <?= $galleryOptionShowDots ? 'true' : 'false' ?>,
                        paginationDirection: '<?= $galleryOptionNavVertical ? 'ttb' : 'ltr' ?>',
                        classes: { page: splidePaginationDotClasses },
                    });

                    this.gallery.on('move', () => {
                        this.isMoving = true;
                    });

                    this.gallery.on('moved', (newIndex) => {
                        this.isMoving = false;
                        this.activeItem = newIndex;
                        this.itemIsVideo = this.images[newIndex].type === 'video';
                        this.activeVideo = this.itemIsVideo && this.videoOptions.autoplay;
                    });

                    this.gallery.mount();
                },
                refreshSlider() {
                    if (!this.gallery) return;
                    this.gallery.refresh();
                },
                goToSlide(index) {
                    if (!this.gallery) return;
                    if (!index) return;
                    this.gallery.go(index);
                },
                setImage() {
                    return this.fullscreen ? this.image.full : this.image.img;
                },
                showCaption() {
                    return (this.image.type === 'image')
                        && this.image.caption
                        && (this.image.caption !== '<?= $escaper->escapeJs($productName) ?>');
                },
                setImageCaption() {
                    return this.image.caption || '<?= $escaper->escapeJs($productName) ?>';
                },
                canShowFullscreenToggle() {
                    return !this.fullscreen && !this.itemIsVideo && !this.isMoving;
                },
                openFullscreen() {
                    this.fullscreen = true;
                },
                closeFullscreen() {
                    this.fullscreen = false;
                },
                fullscreenLabel() {
                    return this.fullscreen ? '<?= $escaper->escapeJs(__('Fullscreen Gallery')) ?>' : false;
                },
                fullscreenRole() {
                    return this.fullscreen && 'dialog';
                },
                scrollLock(use = true) {
                    document.body.style.overflow = use ? "hidden" : "";
                },
                tabLock(target, use = true) {
                    if (!use) {
                        hyva.releaseFocus(target);
                        return;
                    }

                    hyva.trapFocus(target);
                },
                notActiveVideo() {
                    return !this.activeVideo;
                },
                isActiveVideo() {
                    return this.activeItem === this.index && this.activeVideo;
                },
                canShowActiveVideoToggle() {
                    return this.itemIsVideo && !this.activeVideo && !this.isMoving;
                },
                openActiveVideo() {
                    this.activeVideo = true;
                },
                closeActiveVideo() {
                    this.activeVideo = false;
                },
                getVideoData() {
                    const videoUrl = this.image.videoUrl;
                    if (!videoUrl) return;

                    const videoData = {
                        id: null,
                        type: null,
                        src: null,
                        additionalParams: "&autoplay=1",
                        allow: "fullscreen; picture-in-picture; autoplay;"
                    }

                    if (this.videoOptions.loop) {
                        videoData.additionalParams += '&loop=1';
                    }

                    if (videoUrl.match(/youtube\.com|youtu\.be|youtube-nocookie.com/)) {
                        const youtubeRegex = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/;
                        const baseSrc = videoUrl.match(/youtube-nocookie.com/)
                            ? 'https://www.youtube-nocookie.com/embed'
                            : 'https://www.youtube.com/embed';


                        videoData.type = "youtube";
                        videoData.id = videoUrl.match(youtubeRegex)[1];

                        // If rel=0 it only shows related for the channel not external
                        videoData.additionalParams += (this.videoOptions.showRelated ? '&rel=1' : '&rel=0');

                        if (this.videoOptions.loop) {
                            videoData.additionalParams += `&playlist=${videoData.id}`
                        }

                        if (this.videoOptions.allowApi) {
                            videoData.additionalParams += '&enablejsapi=1';
                        }

                        videoData.src = `${baseSrc}/${videoData.id}?origin=<?= $block->getBaseUrl() ?>${videoData.additionalParams}`;
                        videoData.allow += "accelerometer; clipboard-write; encrypted-media; gyroscope"
                    } else if (videoUrl.match(/vimeo\.com/)) {
                        const vimeoRegex = new RegExp([
                            'https?:\\/\\/(?:www\\.|player\\.)?vimeo.com\\/(?:channels\\/(?:\\w+\\/)',
                            '?|groups\\/([^\\/]*)\\/videos\\/|album\\/(\\d+)\\/video\\/|video\\/|)(\\d+)(?:$|\\/|\\?)'
                        ].join(''));
                        const timestamp = new Date().getTime();
                        const baseSrc = "https://player.vimeo.com/video";

                        videoData.type = "vimeo";
                        videoData.id = videoUrl.match(vimeoRegex)[3];
                        if (this.videoOptions.allowApi) {
                            videoData.additionalParams += "&api=1"
                        }
                        videoData.src = `${baseSrc}/${videoData.id}?player_id=vimeo${videoData.id}${timestamp}${videoData.additionalParams}`;
                    }

                    return videoData;
                },
                receiveImages(images) {
                    <?php if ($galleryOptionAppendOnReceive):  ?>
                        const initialUrls = this.initialImages.map(image => image.full);
                        const newImages = images.filter(image => !initialUrls.includes(image.full));
                        this.images = [].concat(this.initialImages, newImages);

                        this.$nextTick(() => {
                            this.refreshSlider();
                            this.goToSlide(newImages ? this.initialImages.length : 0);
                        });
                    <?php else: ?>
                        this.images = images;
                        this.$nextTick(() => this.refreshSlider());
                    <?php endif; ?>
                },
                resetGallery() {
                    this.images = this.initialImages;
                    this.$nextTick(() => this.refreshSlider());
                },
                eventListeners: {
                    ['@keydown.window.escape']() {
                        this.fullscreen = false;
                    },
                    ['@update-gallery.window'](event) {
                        this.receiveImages(event.detail);
                    },
                    ['@reset-gallery.window']() {
                        this.resetGallery();
                    },
                },
            }
        }
        window.addEventListener('alpine:init', () => Alpine.data('initGallery', initGallery), { once: true })
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>
</div>
