<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$uniqueId = '_' . uniqid();
$maxLevel = $block->getmaxLevel() ?: 3;

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menu = $viewModelNavigation->getNavigation(2 + $maxLevel);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

$additionalMenuItems = $block->getAdditionalMenuItemsAfter() ?: [
    'about' => [
        'name' => __('About Us'),
        'url' => '/about-us'
    ],
    'orders-returns' => [
        'name' => __('Orders and Returns'),
        'url' => '/orders-and-returns'
    ],
    'customer-service' => [
        'name' => __('Customer Service'),
        'url' => '/customer-service'
    ],
    'contact' => [
        'name' => __('Contact Us'),
        'url' => '/contact'
    ],
];
$hasAdditionalMenuItems = count($additionalMenuItems) > 0;

$showSettingsNav = $block->getShowSettingsNav() !== null ? $block->getShowSettingsNav() : true;
$showSearch = $block->getShowSearch() !== null ? $block->getShowSearch() : true;
$showSocials = $block->getShowSocials() !== null ? $block->getShowSocials() : true;

$itemClasses = "flex items-center gap-1 py-3 px-6 border-b border-slate-200 hover:text-slate-700 aria-[current=page]:text-blue-700 aria-[current=page]:font-bold -outline-offset-1";
$itemIconSize = 20;
?>

<div class="navigation lg:hidden" x-data="initMobileMenu" @sub-menu-state-change.window="hasActiveSubMenu">
    <button
        type="button"
        class="align-middle"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-controls="mobileMenu"
        @click="open"
    >
        <?= $heroicons->menuHtml('', 32, 32, ["aria-hidden" => "true"]) ?>
    </button>

    <dialog
        id="mobileMenu"
        class="max-h-full h-screen w-full ml-0 open:flex flex-col transition ease-out duration-300 open:duration-500"
        x-show="isOpen"
        x-htmldialog.noscroll="close"
        x-transition:enter-start="-translate-x-full"
        x-transition:enter-end="translate-x-0"
        x-transition:leave-start="translate-x-0"
        x-transition:leave-end="-translate-x-full"
    >
        <div class="border-b border-slate-200">
            <div class="flex items-center gap-2 py-4 px-6">
                <div><?= $block->getChildHtml('logo') ?></div>
                <button
                    type="button"
                    @click="close"
                    class="btn btn-secondary ms-auto p-2 bg-slate-200 text-slate-700"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
                >
                    <?= $heroicons->xHtml('', 24, 24, ["aria-hidden" => "true"]) ?>
                </button>
            </div>
            <?php if ($showSearch && $block->getChildHtml('search')): ?>
                <div class="pb-2 px-6"><?= $block->getChildHtml('search') ?></div>
            <?php endif; ?>
            <div class="flex gap-6 px-6 snap overflow-x-auto overscroll-x-contain text-slate-700">
                <button
                    class="grow py-2 px-4 text-sm font-bold border-b-2 border-transparent aria-expanded:border-current aria-expanded:text-blue-700"
                    aria-controls="mobileMenuMain"
                    :aria-expanded="tabIsMain"
                    @click="setTabTo"
                ><?= $escaper->escapeHtml(__('Shop')) ?></button>
                <?php if ($hasAdditionalMenuItems): ?>
                    <button
                        class="grow py-2 px-4 text-sm font-bold border-b-2 border-transparent aria-expanded:border-current aria-expanded:text-blue-700"
                        aria-controls="mobileMenuExtra"
                        :aria-expanded="tabIsExtra"
                        @click="setTabTo"
                    ><?= $escaper->escapeHtml(__('About')) ?></button>
                <?php endif; ?>
                <?php if ($showSettingsNav): ?>
                    <button
                        class="grow py-2 px-4 text-sm font-bold border-b-2 border-transparent aria-expanded:border-current aria-expanded:text-blue-700"
                        aria-controls="mobileMenuSettings"
                        :aria-expanded="tabIsSettings"
                        @click="setTabTo"
                    ><?= $escaper->escapeHtml(__('Settings')) ?></button>
                <?php endif; ?>
            </div>
        </div>
        <div class="grow relative text-slate-500 overflow-y-auto overflow-x-hidden" :style="lockWrapperScroll">
            <nav
                id="mobileMenuMain"
                x-show="tabIsMain"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Mobile Main Menu')) ?>"
            >
                <ul>
                    <?php foreach ($menu as $item): ?>
                        <?= $block->getLayout()->getBlock('topmenu_mobile_item')
                            ->setItem($item)
                            ->setLevel(0)
                            ->setItemClasses($itemClasses)
                            ->toHtml() ?>
                    <?php endforeach; ?>
                </ul>
            </nav>
            <?php if ($hasAdditionalMenuItems): ?>
                <div id="mobileMenuExtra" x-show="tabIsExtra">
                    <nav aria-label="<?= $escaper->escapeHtmlAttr(__('Mobile Extra Menu')) ?>">
                        <ul>
                            <?php foreach ($additionalMenuItems as $item): ?>
                                <li data-level="0">
                                    <a
                                        href="<?= $escaper->escapeUrl($item['url']) ?>"
                                        class="<?= $escaper->escapeHtmlAttr($itemClasses) ?>"
                                        <?php if (array_key_exists('external', $item)): ?>
                                            target="_blank"
                                            rel="noopener noreferrer"
                                        <?php endif; ?>
                                    ><?= $escaper->escapeHtml($item['name']) ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </nav>
                    <?php if ($showSocials): ?>
                        <?= $block->getChildHtml('socials') ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <?php if ($showSettingsNav): ?>
                <nav
                    id="mobileMenuSettings"
                    x-show="tabIsSettings"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Mobile Store Settings')) ?>"
                >
                    <?= $block->getChildHtml('store-language-switcher') ?>
                    <?= $block->getChildHtml('currency-switcher') ?>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('customer/account/index')) ?>"
                        class="<?= $escaper->escapeHtmlAttr($itemClasses) ?>"
                    >
                        <?= $heroiconsSolid->userCircleHtml('', $itemIconSize, $itemIconSize, ['aria-hidden' => 'true']); ?>
                        <?= $escaper->escapeHtml(__('My Account')) ?>
                    </a>
                </nav>
            <?php endif; ?>
            <div aria-hidden="true" class="sticky bottom-0 h-4 bg-gradient-to-t from-white"></div>
        </div>
        <?= $block->getChildHtml('additional') ?>
    </dialog>
</div>

<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('initMobileMenu', () => ({
            isOpen: false,
            isSubMenuOpen: false,
            isOverflowing: false,
            openTab: 'mobileMenuMain',
            init() {
                Array.from(this.$root.querySelectorAll('a')).forEach(link => {
                    if (link.href === `${window.location.origin}${window.location.pathname}`) {
                        link.setAttribute('aria-current', 'page');
                    }
                });
            },
            open() {
                this.isOpen = true;
            },
            close() {
                this.isOpen = false;
            },
            setTabTo() {
                this.openTab = this.$el.getAttribute('aria-controls');
            },
            tabIsMain() {
                return this.openTab === 'mobileMenuMain';
            },
            tabIsExtra() {
                return this.openTab === 'mobileMenuExtra';
            },
            tabIsSettings() {
                return this.openTab === 'mobileMenuSettings';
            },
            lockWrapperScroll() {
                return this.isSubMenuOpen ? { overflow: 'hidden' } : {}
            },
            hasActiveSubMenu() {
                this.isSubMenuOpen = !!this.$root.querySelector('[data-open]');
            }
        }));

        Alpine.data('initMobileSubMenu', () => ({
            isOpen: false,
            open() {
                this.isOpen = true;
                this.$root.setAttribute('data-open', '');
                this.$nextTick(() => {
                    this.$dispatch('sub-menu-state-change');
                    this.$refs.closeSubMenuBtn.focus();
                    this.toggleInert();
                })
            },
            close() {
                this.isOpen = false;
                this.$root.removeAttribute('data-open');
                this.toggleInert();
                this.$nextTick(() => {
                    this.$dispatch('sub-menu-state-change')
                    this.$refs.openSubMenuBtn.focus();
                })
            },
            toggleInert() {
                const items = this.$root.parentElement.children;

                for (item of items) {
                    if (item.hasAttribute('data-open')) continue;
                    item.toggleAttribute('inert', this.isOpen);
                }
            }
        }));
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>
