<div class="bg-blue-900 p-7">
    <div class="container mx-auto">
        <div class="grid gap-16 sm:grid-cols-3">

            <div class="flex flex-col items-center gap-4 xl:flex-row xl:gap-8">
                <a
                    href="{{store url='customer/account'}}"
                    class="text-white"
                >
                    {{icon "heroicons/solid/user-circle" classes="h-12 w-12 xl:h-16 xl:w-16" width=48 height=48}}
                </a>
                <div class="text-center xl:text-left">
                    <a
                        href="{{store url='customer/account'}}"
                        class="text-xl leading-7 font-semibold text-white"
                    >
                        My account
                    </a>
                    <div class="text-gray-400 leading-6 mt-1 hidden lg:block">
                        Track your order, view and create wishlists or return items.
                    </div>
                </div>
            </div>

            <div class="flex flex-col items-center gap-4 xl:flex-row xl:gap-8">
                <a
                    href="{{store url='contact'}}"
                    class="text-white"
                >
                    {{icon "heroicons/solid/chat-alt-2" classes="h-12 w-12 xl:h-16 xl:w-16" width=48 height=48}}
                </a>
                <div class="text-center xl:text-left">
                    <a
                        href="{{store url='contact'}}"
                        class="text-xl leading-7 font-semibold text-white"
                    >
                        Support
                    </a>
                    <div class="text-gray-400 leading-6 mt-1 hidden lg:block">
                        Check out the FAQ or get in touch with us for assistance.
                    </div>
                </div>
            </div>

            <div class="flex flex-col items-center gap-4 xl:flex-row xl:gap-8">
                <a
                    href="{{store url='home'}}"
                    class="text-white"
                >
                    {{icon "heroicons/solid/mail" classes="h-12 w-12 xl:h-16 xl:w-16" width=48 height=48}}
                </a>
                <div class="text-center xl:text-left">
                    <a
                        href="{{store url='home'}}"
                        class="text-xl leading-7 font-semibold text-white"
                    >
                        Newsletter
                    </a>
                    <div class="text-gray-400 leading-6 mt-1 hidden lg:block">
                        Be the first to know about new arrivals and our best offers.
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
