<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\SwatchRenderer;
use Magento\Framework\Escaper;
use Magento\Swatches\Block\Product\Renderer\Listing\Configurable;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

/** @var Configurable $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

$product = $block->getProduct();
$productId = $product->getId();

$attributes = $block->decorateArray($block->getAllowAttributes());

/** @var SwatchRenderer $swatchRendererViewModel */
$swatchRendererViewModel = $viewModels->require(SwatchRenderer::class);

$layout = $block->getLayout();
$swatchItemBlock = $layout->getBlock('product.swatch.item');
$swatchItemBlock->setData('product_id', $productId);
?>
<?php if ($product->isSaleable() && count($attributes)): ?>

    <script>
        function initListingConfigurableSwatchOptions() {
            const dataset = this.$el.dataset,
                productId = dataset.productId,
                optionConfig = JSON.parse(dataset.config),
                swatchOptions = JSON.parse(dataset.swatchOptions),
                mediaCallback = dataset.mediaCallback;

            const configurableOptionsComponent = initConfigurableOptions(
                productId,
                optionConfig
            );
            const swatchOptionsComponent = initSwatchOptions(swatchOptions);

            const configurableOptionsComponentInit = configurableOptionsComponent.init;

            return Object.assign(
                configurableOptionsComponent,
                swatchOptionsComponent,
                {
                    mediaCallback: mediaCallback,

                    init() {
                        if (this.$root.dataset.hyvaSwatchInitialized === '1') {
                            return;
                        }
                        this.$root.dataset.hyvaSwatchInitialized = '1';

                        configurableOptionsComponentInit.call(this);
                        this.findAllowedAttributeOptions();
                    },

                    changeOption(optionId, value, skipUpdateGallery) {
                        if (value === '') {
                            this.selectedValues = this.removeAttrFromSelection(this.selectedValues, optionId)
                        } else {
                            this.selectedValues[optionId] = value;
                        }

                        this.findSimpleIndex();
                        this.findAllowedAttributeOptions();
                        this.updatePrices();
                        !skipUpdateGallery && this.updateGallery();

                        const candidates = this.findProductIdsForPartialSelection(this.selectedValues);

                        window.dispatchEvent(new CustomEvent('listing-configurable-selection-changed', {
                            detail: {
                                productId: this.productId,
                                optionId,
                                value,
                                productIndex: this.productIndex,
                                selectedValues: this.selectedValues,
                                candidates: candidates,
                                skuCandidates: Object.values(candidates)
                                    .map(id => this.optionConfig.sku?.[id] ?? null)
                                    .filter(Boolean),
                            }
                        }));
                    },

                    updateGallery() {
                        if (!this.productIndex) {
                            return;
                        }

                        fetch(`${this.mediaCallback}?product_id=${this.productIndex}&isAjax=true`, {
                            method: 'GET',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-Requested-With': 'XMLHttpRequest'
                            }
                        })
                            .then(response => response.json())
                            .then(data => {
                                if (data.errors) {
                                    console.warn(data.errors);
                                } else {
                                    data && window.dispatchEvent(
                                        new CustomEvent(
                                            `update-gallery-${this.productId}`,
                                            { detail: data }
                                        )
                                    );
                                }
                            })
                            .catch(error => {
                                console.warn(error)
                            });
                    },

                    preselectQuerystringItems() {
                        const urlQueryParams = new URLSearchParams(window.location.search.replace('?', ''));
                        Object.values(this.optionConfig.attributes).map(attribute => {
                            const skipUpdateGallery = true;
                            urlQueryParams.get(attribute.code) &&
                            this.changeOption(attribute.id, urlQueryParams.get(attribute.code), skipUpdateGallery);
                        });
                    },

                    mouseDown: false,
                    startX: 0,
                    maxScroll: 0,
                    scrollLeft: null,
                    slider: null,

                    scrollEvents: {
                        ['@mousedown'](e) {
                            this.slider = e.target.closest('.snap');
                            if (!this.slider) {
                                return;
                            }
                            this.maxScroll = this.slider.scrollWidth - this.slider.offsetWidth;
                            this.startX = e.pageX - this.slider.offsetLeft;
                            this.scrollLeft = this.slider.scrollLeft;
                            this.mouseDown = true;
                        },
                        ['@mouseout.self']() {
                            this.mouseDown = false;
                        },
                        ['@mouseup']() {
                            this.mouseDown = false;
                        },
                        ['@mousemove'](e) {
                            e.preventDefault();
                            if (!this.mouseDown) {
                                return;
                            }
                            const x = e.pageX - this.slider.offsetLeft;
                            const scroll = x - this.startX;
                            const scrollLeft = this.scrollLeft - scroll;

                            if (scrollLeft > this.maxScroll) {
                                this.slider.scrollLeft = this.maxScroll;
                                return;
                            }
                            this.slider.scrollLeft = this.scrollLeft - scroll;
                        },
                        ['@onselectstart']() {
                            return false;
                        }
                    },

                    resizeEvent() {
                        Array.from(this.$root.querySelectorAll('.snap')).forEach(slider => {
                            slider.scrollLeft = 0;
                        })
                    }
                }
            );
        }

        window.addEventListener('alpine:init', () => Alpine.data('initListingConfigurableSwatchOptions', initListingConfigurableSwatchOptions), { once: true })
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>

    <div
        x-data="initListingConfigurableSwatchOptions"
        data-product-id="<?= $escaper->escapeHtmlAttr($productId) ?>"
        data-config="<?= $escaper->escapeHtmlAttr($block->getJsonConfig()) ?>"
        data-swatch-options="<?= $escaper->escapeHtmlAttr($block->getJsonSwatchConfig()) ?>"
        data-media-callback="<?= $escaper->escapeUrl($block->getMediaCallback()) ?>"
        @private-content-loaded.window="onGetCartData"
        @resize.window="resizeEvent"
        class="mb-2 relative"
    >
        <div>
            <?php foreach ($attributes as $attribute): ?>
                <?php
                $attributeId = $attribute->getAttributeId();
                $productAttribute = $attribute->getProductAttribute();

                if (!$productAttribute->getUsedInProductListing() || !$swatchRendererViewModel->isSwatchAttribute($productAttribute)) {
                    continue;
                }
                ?>
                <div
                    class="swatch-attribute border-t last:border-b border-container <?= $escaper->escapeHtmlAttr($productAttribute->getAttributeCode()) ?>"
                    data-attribute-id="<?= (int) $attributeId ?>"
                >
                    <div class="w-full overflow-x-hidden swatch-attribute-options min-h-14">
                        <div
                            class="flex flex-nowrap w-full overflow-auto snap items-center py-1"
                            id="attribute-label-<?= $escaper->escapeHtmlAttr($productId . '-' . $attributeId) ?>"
                            role="radiogroup"
                            x-bind="scrollEvents"
                            aria-label="<?= $escaper->escapeHtml($productAttribute->getStoreLabel()) ?>"
                        >
                            <template x-for="(item, index) in getAllAttributeOptions" :key="`${item.id}-${index}`">
                                <?= /* @noEscape */ $swatchItemBlock->setData('attribute_id', $attributeId)->toHtml(); ?>
                            </template>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
            <?= /* @noEscape */ $block->getBlockHtml('product.swatch.tooltip') ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
