<div class="my-10">
    <div class="flex-wrap flex justify-between items-baseline mb-2">
        <div class="text-3xl leading-9 font-bold mr-1">Shop by category</div>
        <a
            href="{{store url='home'}}"
            class="block text-lg leading-7 font-semibold text-blue-700"
        >
            Browse all →
        </a>
    </div>
    <div class="gap-4 snap flex overflow-x-auto py-6 md:snap-none md:overflow-x-visible md:gap-4 md:grid md:grid-cols-2">
        <a
            href="{{store url='home'}}"
            class="group block shadow-lg rounded-md overflow-hidden relative h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                w-[calc(100%-theme(spacing.7))] sm:w-[calc(50%-theme(spacing.5))] md:w-full md:first:col-span-full shrink-0 snap-start"
        >
            <img
                alt="A woman doing weight lifting"
                class="absolute w-full h-full object-cover md:group-hover:scale-105 transition duration-300"
                src="https://unsplash.com/photos/h4i9G-de7Po/download?force=true&w=1440&q=80"
                width="1280"
                height="600"
                loading="lazy"
            >
            <div class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800 sm:text-2xl md:text-3xl lg:text-4xl">
                New Arrivals
            </div>
        </a>
        <a
            href="{{store url='home'}}"
            class="group block shadow-lg rounded-md overflow-hidden relative h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                w-[calc(100%-theme(spacing.7))] sm:w-[calc(50%-theme(spacing.5))] md:w-full md:first:col-span-full shrink-0 snap-start"
        >
            <img
                alt="A woman stretching after a run"
                class="absolute w-full h-full object-cover md:group-hover:scale-105 transition duration-300"
                src="https://unsplash.com/photos/v0f_sspLB-o/download?force=true&w=640&q=80"
                width="1280"
                height="600"
                loading="lazy"
            >
            <div class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800 sm:text-2xl md:text-3xl lg:text-4xl">
                Women
            </div>
        </a>
        <a
            href="{{store url='home'}}"
            class="group block shadow-lg rounded-md overflow-hidden relative h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                w-[calc(100%-theme(spacing.7))] sm:w-[calc(50%-theme(spacing.5))] md:w-full md:first:col-span-full shrink-0 snap-start"
        >
            <img
                alt="A man in a hoodie and cap walking away"
                class="absolute w-full h-full object-cover md:group-hover:scale-105 transition duration-300"
                src="https://unsplash.com/photos/dCL6vpW8oJM/download?force=true&w=640&q=80"
                width="1280"
                height="600"
                loading="lazy"
            >
            <div class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800 sm:text-2xl md:text-3xl lg:text-4xl">
                Men
            </div>
        </a>
        <a
            href="{{store url='home'}}"
            class="group block shadow-lg rounded-md overflow-hidden relative h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                w-[calc(100%-theme(spacing.7))] sm:w-[calc(50%-theme(spacing.5))] md:w-full md:first:col-span-full shrink-0 snap-start"
        >
            <img
                alt="A woman showing her sports watch"
                class="absolute w-full h-full object-cover md:group-hover:scale-105 transition duration-300"
                src="https://unsplash.com/photos/SdmdP3UKE6g/download?force=true&w=640&q=80"
                width="1280"
                height="600"
                loading="lazy"
            >
            <div class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800 sm:text-2xl md:text-3xl lg:text-4xl">
                Gear
            </div>
        </a>
        <a
            href="{{store url='home'}}"
            class="group block shadow-lg rounded-md overflow-hidden relative h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                w-[calc(100%-theme(spacing.7))] sm:w-[calc(50%-theme(spacing.5))] md:w-full md:first:col-span-full shrink-0 snap-start"
        >
            <img
                alt="A woman making a knee kick in the air"
                class="absolute w-full h-full object-cover md:group-hover:scale-105 transition duration-300"
                src="https://unsplash.com/photos/2mGaIs51MNU/download?force=true&w=640&q=80"
                width="1280"
                height="600"
                loading="lazy"
            >
            <div class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800 sm:text-2xl md:text-3xl lg:text-4xl">
                Training
            </div>
        </a>
    </div>
</div>
