<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SwatchRenderer;
use Magento\Framework\Escaper;
use Magento\Swatches\Block\Product\Renderer\Listing\Configurable;

/** @var Configurable $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */

// phpcs:disable Generic.Files.LineLength.TooLong

$product = $block->getProduct();
$productId = (int) $product->getId();

$attributes = $block->decorateArray($block->getAllowAttributes());

/** @var SwatchRenderer $swatchRendererViewModel */
$swatchRendererViewModel = $viewModels->require(SwatchRenderer::class);

$layout = $block->getLayout();
$swatchItemBlock = $layout->getBlock('product.swatch.item');

if (!$swatchItemBlock) {
    return;
}

$swatchItemBlock->setData('product_id', $productId);
?>

<?php if ($product->isSaleable() && count($attributes)): ?>
    <script>
        function initConfigurableSwatchOptions_<?= $productId ?>() {
            const configurableOptionsComponent = initConfigurableOptions(
                '<?= $productId ?>',
                <?= /* @noEscape */ $block->getJsonConfig() ?>
            );
            const swatchOptionsComponent = initSwatchOptions(
                <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>
            );

            return Object.assign(
                configurableOptionsComponent,
                swatchOptionsComponent,
                {
                    productId: '<?= $productId ?>',
                    mediaCallback: "<?= $escaper->escapeJs($escaper->escapeUrl($block->getMediaCallback())) ?>",

                    getListingAttributeOptions(attributeId) {
                        const options = this.getAllAttributeOptions(attributeId);
                        return Array.isArray(options) ? options : [];
                    },

                    hasListingAttributeOptions(attributeId) {
                        return this.getListingAttributeOptions(attributeId).length > 0;
                    },

                    changeOption(optionId, value, skipUpdateGallery) {
                        this.selectedValues[optionId] = value;
                        this.findSimpleIndex();
                        this.findAllowedAttributeOptions();
                        this.updatePrices();
                        !skipUpdateGallery && this.updateGallery();
                    },

                    updateGallery() {
                        if (!this.productIndex) {
                            return;
                        }

                        fetch(`${this.mediaCallback}?product_id=${this.productIndex}&isAjax=true`, {
                            method: 'GET',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-Requested-With': 'XMLHttpRequest'
                            }
                        })
                            .then(response => response.json())
                            .then(data => {
                                if (data.errors) {
                                    console.warn(data.errors);
                                } else {
                                    const image = data && data.medium;

                                    if (image) {
                                        window.dispatchEvent(
                                            new CustomEvent(
                                                "update-gallery-<?= $productId ?>",
                                                { detail: image }
                                            )
                                        );
                                    }
                                }
                            })
                            .catch(error => {
                                console.warn(error);
                            });
                    },

                    preselectQuerystringItems() {
                        const urlQueryParams = new URLSearchParams(window.location.search.replace('?', ''));
                        const attributes = this.optionConfig && this.optionConfig.attributes
                            ? this.optionConfig.attributes
                            : {};

                        Object.values(attributes).forEach(attribute => {
                            const skipUpdateGallery = false;

                            if (urlQueryParams.get(attribute.code) !== null) {
                                let optionId = urlQueryParams.get(attribute.code);

                                if (Array.isArray(attribute.options)) {
                                    attribute.options.forEach(option => {
                                        if (option.label === optionId) {
                                            optionId = option.id;
                                        }
                                    });
                                }

                                this.changeOption(attribute.id, optionId, skipUpdateGallery);
                            }
                        });
                    },

                    mouseDown: false,
                    startX: 0,
                    maxScroll: 0,
                    scrollLeft: null,
                    slider: null,

                    scrollEvents: {
                        ['@mousedown'](e) {
                            this.slider = e.target.closest('.snap');

                            if (!this.slider) {
                                return;
                            }

                            this.maxScroll = this.slider.scrollWidth - this.slider.offsetWidth;
                            this.startX = e.pageX - this.slider.offsetLeft;
                            this.scrollLeft = this.slider.scrollLeft;
                            this.mouseDown = true;
                        },

                        ['@mouseout.self']() {
                            this.mouseDown = false;
                        },

                        ['@mouseup']() {
                            this.mouseDown = false;
                        },

                        ['@mousemove'](e) {
                            e.preventDefault();

                            if (!this.mouseDown) {
                                return;
                            }

                            const x = e.pageX - this.slider.offsetLeft;
                            const scroll = x - this.startX;
                            const scrollLeft = this.scrollLeft - scroll;

                            if (scrollLeft > this.maxScroll) {
                                this.slider.scrollLeft = this.maxScroll;
                                return;
                            }

                            this.slider.scrollLeft = this.scrollLeft - scroll;
                        },

                        ['@onselectstart']() {
                            return false;
                        }
                    },

                    resizeEvent() {
                        Array.from(this.$el.querySelectorAll('.snap')).forEach(slider => {
                            slider.scrollLeft = 0;
                        });
                    }
                }
            );
        }
    </script>
    <?php $hyvaCsp->registerInlineScript(); ?>

    <div
        x-data="initConfigurableSwatchOptions_<?= $productId ?>()"
        x-init="findAllowedAttributeOptions();"
        @private-content-loaded.window="onGetCartData($event.detail.data)"
        @resize.window="resizeEvent()"
        class="relative"
        data-product-id="<?= $productId ?>"
    >
        <div>
            <?php foreach ($attributes as $attribute): ?>
                <?php
                $attributeId = (int) $attribute->getAttributeId();
                $productAttribute = $attribute->getProductAttribute();
                ?>

                <?php if (
                    !$productAttribute->getUsedInProductListing()
                    || !$swatchRendererViewModel->isSwatchAttribute($productAttribute)
                ) {
                    continue;
                } ?>

                <div
                    class="swatch-attribute border-t last:border-b border-container <?= $escaper->escapeHtmlAttr($productAttribute->getAttributeCode()) ?>"
                >
                    <div class="w-full overflow-x-hidden swatch-attribute-options">
                        <div
                            class="flex flex-nowrap w-full overflow-auto transition-all snap items-center py-1 min-h-14"
                            role="radiogroup"
                            x-spread="scrollEvents"
                            aria-label="<?= $escaper->escapeHtml($productAttribute->getStoreLabel()) ?>"
                        >
                            <template x-if="hasListingAttributeOptions(<?= $attributeId ?>)">
                                <template
                                    x-for="(item, index) in getListingAttributeOptions(<?= $attributeId ?>)"
                                    :key="item.id"
                                >
                                    <?= /* @noEscape */ $swatchItemBlock->setData('attribute_id', $attributeId)->toHtml(); ?>
                                </template>
                            </template>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
