<div class="p-6 leading-6 text-gray-600">

    <div class="grid gap-4 lg:grid-cols-3">

        <div class="flex items-center gap-6 bg-blue-100 rounded-xl p-6 lg:px-12 lg:flex-col lg:gap-4">
            <div>
                <div class="w-16 h-16 bg-blue-600 text-white rounded-full flex justify-center items-center">
                    {{icon "heroicons/solid/shield-check" classes="w-12 h-12 fill-current" width=48 height=48}}
                </div>
            </div>
            <div class="lg:text-center">
                <div class="text-xl text-gray-800 font-medium leading-7 mb-2">
                    Safe and secure
                </div>
                <div>
                    Sed posuere venenatis nisl, et vestibulum massa cursus vitae. Vivamus eu tempus mauris. Aliquam
                    viverra mauris quam, maximus placerat arcu tristique sed. Nam at tincidunt lorem.
                </div>
            </div>
        </div>

        <div class="flex items-center gap-6 bg-blue-100 rounded-xl p-6 lg:px-12 lg:flex-col lg:gap-4">
            <div>
                <div class="w-16 h-16 bg-blue-600 text-white rounded-full flex justify-center items-center">
                    {{icon "heroicons/solid/truck" classes="w-12 h-12 fill-current" width=48 height=48}}
                </div>
            </div>
            <div class="lg:text-center">
                <div class="text-xl text-gray-800 font-medium leading-7 mb-2">
                    Free shipping
                </div>
                <div>
                    Aliquam erat volutpat. Cras venenatis ullamcorper metus at vulputate. Pellentesque habitant morbi
                    tristique senectus et netus et malesuada fames ac turpis egestas.
                </div>
            </div>
        </div>

        <div class="flex items-center gap-6 bg-blue-100 rounded-xl p-6 lg:px-12 lg:flex-col lg:gap-4">
            <div>
                <div class="w-16 h-16 bg-blue-600 text-white rounded-full flex justify-center items-center">
                    {{icon "heroicons/solid/gift" classes="w-12 h-12 fill-current" width=48 height=48}}
                </div>
            </div>
            <div class="lg:text-center">
                <div class="text-xl text-gray-800 font-medium leading-7 mb-2">
                    Amazing gift-wrapping
                </div>
                <div>
                    Integer in ante non felis ornare tempus. Nam ut mi id lorem maximus ornare sit amet vitae enim.
                    Nam a dictum sapien. Proin dictum sodales velit at finibus.
                </div>
            </div>
        </div>

    </div>
</div>