<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HyvaCsp $hyvaCsp */

$hideOnScrollDown = $block->getHideOnScrollDown() !== null
    ? (bool) $block->getHideOnScrollDown()
    : true;
$scrollOffset = (int) $block->getScrollOffset() ?: 100;
$enableCssOnlyStickyStyle = $block->getEnableCssOnlyStickyStyle() !== null
    ? (bool) $block->getEnableCssOnlyStickyStyle()
    : false;
?>

<?php if (!$enableCssOnlyStickyStyle || $hideOnScrollDown): ?>
<script>
    <?php if (!$enableCssOnlyStickyStyle): ?>
        document.addEventListener('DOMContentLoaded', () => {
            const pageHeader = document.querySelector('.page-header');
            if (!pageHeader) return;

            const observer = new IntersectionObserver(([e]) => {
                e.target.dataset.sticky = e.intersectionRatio < 1
            }, { threshold: 1 });
            observer.observe(pageHeader)
        });
    <?php endif; ?>

    <?php if ($hideOnScrollDown): ?>
        window.addEventListener('scrollPosition', () => {
            const scrollOffset = <?= $escaper->escapeJs($scrollOffset) ?>;
            document.documentElement.toggleAttribute('data-header-can-sticky', window.pageYOffset > scrollOffset);
        });
    <?php endif; ?>
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<?php endif; ?>

<style>
    <?php if ($enableCssOnlyStickyStyle): ?>
        @keyframes add-sticky {
            to {
                box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
                background-color: #fff;
            }
        }
    <?php endif; ?>

    .page-header {
        z-index: 30;
        position: sticky;
        top: -1px;
        background-color: #fff;
        transition: background-color 150ms, color 150ms, box-shadow 150ms, translate 300ms;
    }

    <?php if ($enableCssOnlyStickyStyle): ?>
        @supports (animation-timeline: scroll()) {
            .page-header {
                background-color: transparent;
                transition: translate 300ms;
                animation: add-sticky linear both;
                animation-timeline: scroll();
                animation-range: 0 6px;
            }
        }
    <?php endif; ?>

    <?php if (!$enableCssOnlyStickyStyle): ?>
        .page-header[data-sticky="false"] {
            background-color: transparent;
        }

        .page-header[data-sticky="true"] {
            box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
        }
    <?php endif; ?>

    <?php if ($hideOnScrollDown): ?>
        html[data-header-can-sticky][data-scroll-dir-y="down"] .page-header {
            box-shadow: none;
            translate: 0 -100%;
            transition: background-color 150ms, color 150ms, box-shadow 150ms, translate 300ms 150ms;
        }
    <?php endif; ?>
</style>
