<div class="relative card card-interactive flex items-start gap-6 overflow-clip">
    <img
        src="https://unsplash.com/photos/WqI-PbYugn4/download?force=true&auto=format&fit=crop&w=150&h=150&q=80"
        width="150"
        height="150"
        loading="lazy"
        class="max-w-1/2 sm:shrink-0"
    >
    <div class="prose grow">
        <p class="text-2xl"><strong>Hit the court in style.</strong></p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            Quia ut aliquid, numquam totam nemo ex sed suscipit veniam, at, dolores neque nisi ea!
            Eum earum consequuntur, eos magni ducimus nulla!
        </p>
        <p class="mt-8 mb-0">
            <a
                href="{{store url='home'}}"
                class="btn inline-flex before:absolute before:inset-0"
            >
                Shop our tennis gear →
            </a>
        </p>
    </div>
</div>
