<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

$label = $block->getData('label') ?? __('Compare Products');
$urlPath = $block->getData('path') ?? 'catalog/product_compare/index';
?>

<a
    id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
    class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100 relative"
    href="<?= $escaper->escapeUrl($block->getUrl($urlPath)) ?>"
    title="<?= $escaper->escapeHtmlAttr($label) ?>"
    x-data="initCompareHeader"
    @private-content-loaded.window="receiveCompareData"
>
    <?= $escaper->escapeHtml($label) ?>
    <template x-if="itemCount">
        <span class="tabular-nums" x-text="itemCountLabel"></span>
    </template>
</a>
