<article class="max-w-full prose prose-slate lg:prose-lg prose-li:my-0 prose-p:my-8 prose-lead:mt-0 md:prose-h1:text-5xl">
    <hgroup class="md:mb-12 space-y-4 prose-p:font-bold prose-p:text-blue-700 prose-p:text-2xl prose-p:md:text-3xl">
        <p class="!my-0">404</p>
        <h1>Page not found</h1>
    </hgroup>
    <p>Sorry, we couldn’t find what you were looking for.</p>
    <p class="not-prose">
        <a href="/" class="inline-flex gap-1 btn btn-secondary">
            {{icon "heroicons/solid/arrow-left" width=16 height=16 aria-hidden=true}}
            <span>Back to home</span>
        </a>
    </p>
    <hr class="mt-20 mb-10 lg:mt-24 lg:mb-16 border-slate-300">
    <section aria-label="Or explore our Categories" class="not-prose grid grid-cols-2 lg:grid-cols-4 gap-1 sm:gap-4">
        <figure class="group grid relative">
            <picture class="row-start-1 col-start-1">
                <source media="(max-width: 639px)" srcset="https://unsplash.com/photos/UTLqS1wa104/download?force=true&auto=format&fit=crop&w=300&q=80">
                <img src="https://unsplash.com/photos/UTLqS1wa104/download?force=true&auto=format&fit=crop&w=720&q=80" alt="" width="300" height="360" loading="lazy" class="w-full aspect-[3/4] object-cover group-hover:opacity-70 transition-opacity duration-500">
            </picture>
            <figcaption class="row-start-1 col-start-1 isolate flex flex-col justify-end items-center p-2 sm:py-8 bg-gradient-to-t from-slate-800/50 via-transparent to-transparent text-white font-bold sm:text-lg">
                <a href="{{store url='home'}}" class="before:absolute before:inset-0" aria-label="Checkout our Tennis products">Tennis</a>
            </figcaption>
        </figure>
        <figure class="group grid relative">
            <picture class="row-start-1 col-start-1">
                <source media="(max-width: 639px)" srcset="https://unsplash.com/photos/lwberC4uK8Q/download?force=true&auto=format&fit=crop&w=300&q=80">
                <img src="https://unsplash.com/photos/lwberC4uK8Q/download?force=true&auto=format&fit=crop&w=720&q=80" alt="" width="300" height="360" loading="lazy" class="w-full aspect-[3/4] object-cover group-hover:opacity-70 transition-opacity duration-500">
            </picture>
            <figcaption class="row-start-1 col-start-1 isolate flex flex-col justify-end items-center p-2 sm:py-8 bg-gradient-to-t from-slate-800/50 via-transparent to-transparent text-white font-bold sm:text-lg">
                <a href="{{store url='home'}}" class="before:absolute before:inset-0" aria-label="Checkout our exclusive Hyvä products">Only at Hyvä</a>
            </figcaption>
        </figure>
        <figure class="group grid relative">
            <picture class="row-start-1 col-start-1">
                <source media="(max-width: 639px)" srcset="https://unsplash.com/photos/FYD0o4Q5lXE/download?force=true&auto=format&fit=crop&w=300&q=80">
                <img src="https://unsplash.com/photos/FYD0o4Q5lXE/download?force=true&auto=format&fit=crop&w=720&q=80" alt="" width="300" height="360" loading="lazy" class="w-full aspect-[3/4] object-cover group-hover:opacity-70 transition-opacity duration-500">
            </picture>
            <figcaption class="row-start-1 col-start-1 isolate flex flex-col justify-end items-center p-2 sm:py-8 bg-gradient-to-t from-slate-800/50 via-transparent to-transparent text-white font-bold sm:text-lg">
                <a href="{{store url='home'}}" class="before:absolute before:inset-0" aria-label="Checkout our Basketball products">Basketball</a>
            </figcaption>
        </figure>
        <figure class="group grid relative">
            <picture class="row-start-1 col-start-1">
                <source media="(max-width: 639px)" srcset="https://unsplash.com/photos/Z0xdndoFc3k/download?force=true&auto=format&fit=crop&w=300&q=80">
                <img src="https://unsplash.com/photos/Z0xdndoFc3k/download?force=true&auto=format&fit=crop&w=720&q=80" alt="" width="300" height="360" loading="lazy" class="w-full aspect-[3/4] object-cover group-hover:opacity-70 transition-opacity duration-500">
            </picture>
            <figcaption class="row-start-1 col-start-1 isolate flex flex-col justify-end items-center p-2 sm:py-8 bg-gradient-to-t from-slate-800/50 via-transparent to-transparent text-white font-bold sm:text-lg">
                <a href="{{store url='home'}}" class="before:absolute before:inset-0" aria-label="Checkout our Gym products">Gym</a>
            </figcaption>
        </figure>
    </section>
</article>
