<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$fallbackImage = 'https://unsplash.com/photos/F7D7oWb8aO0/download?force=true&auto=format&fit=crop&w=1280&h=640&q=80';
$image = $block->getData('image') ?? [
    'src' => $fallbackImage,
    'alt' => ''
];
$imageClasses = 'w-full object-cover';
$imageLoading = $block->getData('loading') ?? 'lazy';

$link = $block->getData('link') ?? [
    'url' => $block->getUrl('home'),
    'label' => __('Check it out!'),
];

$linkAppearance = $block->getLinkAppearance() ?: 'btn-primary'; // 'btn-primary', 'btn-secondary', 'btn', 'link', 'overlay'

$useLinkOverlay = $block->getUseLinkOverlay() !== null ? $block->getUseLinkOverlay() : $linkAppearance === "overlay";
$useReverse = $block->getUseReverse() !== null ? $block->getUseReverse() : false;
$useHiddenLink = $linkAppearance === "overlay";

$position = (string) $block->getContentAlignment() ?: 'center stretch';
$textAlign = (string) $block->getTextAlign();
$bgColor = (string) $block->getBackgroundColor() ?: '#1e293b'; // slate-800
$fgColor = (string) $block->getTextColor() ?: '#f8fafc'; // slate-50
$titleColor = (string) $block->getTitleColor();

// Styles
$bannerClasses = implode(' ', array_filter([
    'relative grid grid-cols-1 md:grid-cols-2',
    $useHiddenLink ? 'transition-[outline-offset] focus-within:outline focus-within:outline-2 focus-within:outline-offset-4 focus-within:outline-primary' : '',
    $block->getCssClasses()
]));
$bannerStyles = implode('; ', array_filter([
    $bgColor ? "--banner-bg: {$bgColor}" : '',
    $fgColor ? "--banner-color: {$fgColor}" : '',
    ($bgColor || $fgColor) ? 'background: var(--banner-bg); color: var(--banner-color)' : '',
]));

$bannerContentClasses = implode(' ', array_filter([
    'isolate p-6 md:p-12',
    $useReverse ? 'order-first' : ''
]));

$bannerContentStyles = implode('; ', array_filter([
    $position ? "place-self: {$position}" : '',
    $textAlign ? "text-align: {$textAlign}" : '',
]));

$bannerTitleStyles = implode('; ', array_filter([
    $titleColor ? "color: {$titleColor}" : ''
]));

$bannerLinkClasses = implode(' ', array_filter([
    $linkAppearance === 'btn-primary' ? 'btn btn-primary inline-flex' : '',
    $linkAppearance === 'btn-secondary' ? 'btn btn-secondary inline-flex' : '',
    $linkAppearance === 'btn' ? 'btn inline-flex' : '',
    $linkAppearance === 'link' ? 'font-medium underline hover:no-underline' : '',
    $useLinkOverlay ? 'before:absolute before:inset-0 before:transition-opacity before:duration-500 before:opacity-0 before:bg-current hover:before:opacity-10' : ''
]));

// Content
$title = (string) $block->getTitle() ?: __("Hit the court in style.");
$subtitle = (string) $block->getSubtitle() ?: '';
?>
<div
    class="<?= $escaper->escapeHtmlAttr($bannerClasses) ?>"
    style="<?= $escaper->escapeHtmlAttr($bannerStyles) ?>"
>
    <picture>
        <?php if ($imageDesktop = $block->getData('desktop_image') ?? ''): ?>
            <source
                srcset="<?= $escaper->escapeUrl($imageDesktop) ?>"
                media="(min-width: 1024px)"
            >
        <?php endif; ?>
        <img
            src="<?= $escaper->escapeUrl($image['src'] ?? '') ?>"
            width="<?= $escaper->escapeHtmlAttr($image['width'] ?? '1280') ?>"
            height="<?= $escaper->escapeHtmlAttr($image['height'] ?? '640') ?>"
            alt="<?= $escaper->escapeUrl($image['alt'] ?? '') ?>"
            loading="<?= $escaper->escapeHtmlAttr($imageLoading) ?>"
            class="<?= $escaper->escapeHtmlAttr($imageClasses) ?>"
        >
    </picture>
    <div
        class="<?= $escaper->escapeHtmlAttr($bannerContentClasses) ?>"
        style="<?= $escaper->escapeHtmlAttr($bannerContentStyles) ?>"
    >
        <p
            class="text-3xl lg:text-6xl text-balance mb-2"
            style="<?= $escaper->escapeHtmlAttr($bannerTitleStyles) ?>"
        >
            <strong><?= $escaper->escapeHtml($title) ?></strong>
        </p>
        <?php if ($subtitle): ?>
            <p class="text-lg lg:text-2xl font-medium my-2">
                <?= $escaper->escapeHtml($subtitle) ?>
            </p>
        <?php endif; ?>
        <?php if ($linkUrl = $link['url'] ?? ''): ?>
            <div <?= $useHiddenLink ? '' : 'class="mt-6 inline-flex flex-wrap items-center gap-4"' ?>>
                <a
                    href="<?= $escaper->escapeUrl($linkUrl) ?>"
                    <?= ($link['open_in_new'] ?? false) ? 'target="_blank" rel="noopener"' : '' ?>
                    class="<?= $escaper->escapeHtmlAttr($bannerLinkClasses) ?>"
                >
                    <span <?= $useHiddenLink ? 'class="sr-only"' : '' ?>>
                        <?= $escaper->escapeHtml($link['label'] ?? __('Go to %1', $linkUrl)) ?>
                    </span>
                </a>
            </div>
        <?php endif; ?>
    </div>
</div>
