<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Review\Block\Product\ReviewRenderer;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;

/** @var ReviewRenderer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);
/** @var HyvaCsp $hyvaCsp */

$rating = $block->getRatingSummary();
$ratingSteps = 5;
$starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
$starFragment = $rating / 100 * $ratingSteps - $starsFilled;
$starsEmpty = floor($ratingSteps - $starsFilled - $starFragment);
$productName = $block->getProduct()->getName();
$productId = $block->getProduct()->getId();
$reviewCount = $block->getReviewsCount();
?>

<?php if ($block->isReviewEnabled() && $reviewCount): ?>
    <div
        x-data="initRating"
        x-defer="intersect"
        class="rating-summary flex items-center gap-1 text-sm"
        @keyup.enter="scrollToRatings"
        @click="scrollToRatings"
        :class="scrollToRatingsClasses"
        <?php if (!$rating): ?>
            title="<?= $escaper->escapeHtmlAttr(__('Be the first to review this product')) ?>"
        <?php endif; ?>
        data-arial-label-review-section="<?= $escaper->escapeHtmlAttr(__('%1 rating. %2 out of %3 stars. Click to go to reviews.', $productName, $starsFilled + $starFragment, $ratingSteps)) ?>"
        data-aria-label-no-review-section="<?= $escaper->escapeHtmlAttr(__('%1 rating. %2 out of %3 stars', $productName, $starsFilled + $starFragment, $ratingSteps)) ?>"
        :tabindex="scrollToRatingsTabIndex"
        :aria-label="scrollToRatingsAriaLabel"
        :role="elementRole"
    >
        <?= $heroiconsSolid->starHtml('text-yellow-500 mt-0.5', 20, 20, ['aria-hidden' => 'true']); ?>
        <span class="font-bold text-slate-800">
            <?= $rating / 20 ?>
        </span>
        <span class="text-blue-500">
            (<span><?= $reviewCount ?></span>)
        </span>
    </div>

    <script>
        function initRating() {
            return {
                reviewsSection: document.getElementById('customer-review-list')
                    || document.getElementById('customer-reviews')
                    || document.getElementById('review-form'),
                scrollToRatingsClasses() {
                    return {
                        'cursor-pointer': this.reviewsSection
                    }
                },
                scrollToRatingsTabIndex() {
                    return this.reviewsSection ? '0' : '-1';
                },
                scrollToRatingsAriaLabel() {
                    return this.reviewsSection
                        ? this.$el.dataset.ariaLabelReviewSection
                        : this.$el.dataset.ariaLabelNoReviewSection

                },
                elementRole() {
                    return this.reviewsSection ? 'button' : 'img';
                },
                scrollToRatings() {
                    let scrollTimeout = null

                    if (!this.reviewsSection) {
                        return
                    }

                    addEventListener('scroll', () => {
                        clearTimeout(scrollTimeout);

                        scrollTimeout = setTimeout(() => {
                            if (this.reviewsSection) {
                                this.reviewsSection.focus()
                            }
                        }, 50);
                    }, { once: true });

                    this.reviewsSection.scrollIntoView({behavior: 'smooth'})
                }
            }
        }
        window.addEventListener('alpine:init', () => Alpine.data('initRating', initRating), {once: true})
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>
<?php endif; ?>
