<div class="relative card card-interactive flex flex-col overflow-clip p-0">
    <picture>
        <source
            media="(min-width: 1024px)"
            srcset="https://unsplash.com/photos/WqI-PbYugn4/download?force=true&auto=format&fit=crop&w=1500&h=480&q=80"
        >
        <img
            src="https://unsplash.com/photos/WqI-PbYugn4/download?force=true&auto=format&fit=crop&w=1024&h=480&q=80"
            width="1500"
            height="480"
            loading="lazy"
        >
    </picture>
    <div class="card-content p-6 prose">
        <p class="text-2xl"><strong>Hit the court in style.</strong></p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            Quia ut aliquid, numquam totam nemo ex sed suscipit veniam, at, dolores neque nisi ea!
            Eum earum consequuntur, eos magni ducimus nulla!
        </p>
        <p class="mt-8 mb-0">
            <a
                href="{{store url='home'}}"
                class="btn inline-flex before:absolute before:inset-0"
            >
                Shop our tennis gear →
            </a>
        </p>
    </div>
</div>
