<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$sliderShowArrows = $block->getShowArrows() !== null ? $block->getShowArrows() : "end";
$sliderShowPager = $block->getShowPager() !== null ? (bool) $block->getShowPager() : true;
$loadFirstEager = (bool) $block->getLoadFirstEager();

$pagerClasses = "hidden sm:flex gap-4 justify-center items-center mt-7 absolute w-full bottom-8";
$markerClasses = "w-4 h-4 rounded-full shadow-md cursor-pointer ring-4 ring-transparent bg-white hover:bg-blue-600 transition aria-[current=true]:ring-white aria-[current=true]:bg-blue-600";

$items = [
    [
        // All options
        'image_url' => 'https://unsplash.com/photos/a1_DQQhtLVc/download?force=true&auto=format&fit=crop&w=1280&q=80',
        'image_alt' => __('New Arrivals'),
        'text_small' => __('New Arrivals'),
        'text_large' => __('(Track)Suit Up!'),
        'url' => $block->getUrl('home'),
    ],
    [
        'image_url' => 'https://unsplash.com/photos/HyvE5SiKMUs/download?force=true&auto=format&fit=crop&w=1280&q=80',
        'image_alt' => __('Summer Collection'),
    ],
    [
        'image_url' => 'https://unsplash.com/photos/zlPmPfXfr4A/download?force=true&auto=format&fit=crop&w=1280&q=80',
        'text_small' => __('Winter Collection'),
        'text_large' => __('Show Your Style'),
    ],
    [
        'image_url' => 'https://unsplash.com/photos/X6jtULYJQz8/download?force=true&auto=format&fit=crop&w=1280&q=80',
        'text_small' => __('Sale'),
        'text_large' => __('10% Off, Only This Weekend'),
    ],
];
?>

<section
    class="relative my-20"
    aria-label="<?= $escaper->escapeHtml(__('Latest items')) ?>"
    x-data
    <?php if ($sliderShowPager): ?>
        x-snap-slider.auto-pager
        data-pager-class="<?= $escaper->escapeHtmlAttr($pagerClasses) ?>"
        data-marker-class="<?= $escaper->escapeHtmlAttr($markerClasses) ?>"
    <?php else: ?>
        x-snap-slider
    <?php endif; ?>
>
    <?php if ($sliderShowArrows): ?>
        <nav
            class="z-10 flex gap-2 justify-between absolute bottom-4 sm:static
                <?= $sliderShowArrows === "end" ? "right-4" : ($sliderShowArrows === "start" ? "left-4" : "inset-x-4") ?>"
            aria-label="<?= $escaper->escapeHtml(__('Latest items controls')) ?>"
        >
            <button
                type="button"
                data-prev
                class="sm:z-10 sm:absolute sm:top-1/2 sm:-translate-y-1/2 sm:left-4
                    shrink-0 p-2.5 rounded-full transition bg-white text-primary shadow
                    disabled:opacity-30 hover:shadow-primary/30 focus:shadow-primary/30"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Previous Slide')) ?>"
            >
                <?= /** @noEscape */ $heroicons->arrowLeftHtml() ?>
            </button>
            <button
                type="button"
                data-next
                class="sm:z-10 sm:absolute sm:top-1/2 sm:-translate-y-1/2 sm:right-4
                    shrink-0 p-2.5 rounded-full transition bg-white text-primary shadow
                    disabled:opacity-30 hover:shadow-primary/30 focus:shadow-primary/30"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Go to Next Slide')) ?>"
            >
                <?= /** @noEscape */ $heroicons->arrowRightHtml() ?>
            </button>
        </nav>
    <?php endif; ?>
    <div data-track class="snap relative grid grid-flow-col auto-cols-[100%] overflow-x-auto overscroll-x-contain">
        <?php foreach ($items as $index => $item): ?>
            <?php
                $itemTextLarge = $item['text_large'] ?? '';
                $itemTextSmall = $item['text_small'] ?? '';
            ?>
            <figure class="shrink-0 grid *:row-start-1 *:col-start-1 w-full">
                <img
                    class="w-full h-[460px] md:h-[580px] lg:h-[800px] object-cover"
                    src="<?= $escaper->escapeHtmlAttr($item['image_url']) ?>"
                    alt="<?= $escaper->escapeHtmlAttr($item['image_alt'] ?? $item['text_small'] ?? '') ?>"
                    width="1280"
                    height="853"
                    loading="<?= $escaper->escapeHtmlAttr(($loadFirstEager && $index === 0 ? 'eager' : 'lazy')) ?>"
                >
                <?php if ($itemTextSmall || $itemTextLarge): ?>
                    <figcaption class="relative col-start-1 row-start-1 self-end px-6 pt-12 pb-20 sm:pb-24 bg-gradient-to-t from-gray-800/50 to-transparent text-white text-center uppercase">
                        <?php if ($itemTextSmall): ?>
                            <p class="text-base sm:text-xl sm:mb-3 last:mb-0 sm:leading-7 font-semibold drop-shadow-md">
                                <?= $escaper->escapeHtml($itemTextSmall) ?>
                            </p>
                        <?php endif; ?>
                        <?php if ($itemTextLarge): ?>
                            <p class="text-2xl sm:text-3xl md:text-5xl sm:leading-none font-bold drop-shadow-md">
                                <?= $escaper->escapeHtml($itemTextLarge) ?>
                            </p>
                        <?php endif; ?>
                    </figcaption>
                <?php endif; ?>
            </figure>
        <?php endforeach; ?>
    </div>
</section>
