<div class="flex flex-col md:flex-row md:items-start gap-4 my-6">
    <picture class="shrink-0">
        <source
            media="(min-width: 768px)"
            srcset="https://unsplash.com/photos/q7lul0zB0Lg/download?force=true&auto=format&fit=crop&w=180&q=80"
        >
        <source srcset="https://unsplash.com/photos/CQzCMx_wvk4/download?force=true&auto=format&fit=crop&w=640&q=80">
        <img
            src="https://unsplash.com/photos/CQzCMx_wvk4/download?force=true&auto=format&fit=crop&w=640&q=80"
            alt="Relay runner"
            width="640"
            height="400"
            loading="lazy"
            class="m-0 md:w-48"
        >
    </picture>
    <div class="space-y-2">
        <p class="mt-0 mb-2"><strong>All new material</strong></p>
        <p>Our go-to model for training relies on a lighter, more breathable upper than our previous edition to complement our standards of durability and comfort, so that you can float through your cardio, power through your lifts and dominate your workouts.</p>
    </div>
</div>
