<article class="lg:grid lg:grid-cols-2 lg:gap-x-2 bg-zinc-100">
    <div class="grid">
        <img
            src="https://unsplash.com/photos/ByUAo3RpA6c/download?force=true&auto=format&fit=crop&w=720&q=80"
            alt="Man holding bike while standing on gray mountain"
            class="col-start-1 row-start-1 lg:w-full lg:h-full lg:object-cover"
            width="720"
            height="949"
            loading="lazy"
        >
        <div aria-hidden="true" class="lg:hidden col-start-1 row-start-1 self-end pt-16 pb-8 px-6 bg-gradient-to-t from-slate-800/75 text-white">
            <span class="inline-block mb-2 px-2 py-1 rounded bg-blue-800 text-blue-100 text-lg font-semibold uppercase">
                About us
            </span>
            <div class="text-4xl font-bold lg:text-5xl">
                Everything you need to know
            </div>
        </div>
    </div>

    <div class="p-6 max-w-full prose prose-slate prose-p:text-slate-500 prose-lead:text-slate-600 prose-li:my-0 prose-p:my-8 prose-lead:mt-0 md:prose-h1:text-5xl">
        <div class="sr-only lg:not-sr-only">
            <div class="mb-12 space-y-2">
                <span class="inline-block px-2 py-1 rounded bg-blue-100 text-blue-600 text-xl font-semibold uppercase">About us</span>
                <h1>Everything you need to know</h1>
            </div>
        </div>
        <p class="lead text-lg font-medium">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu neque aliquam metus porta
            sagittis. Nunc velit ligula, vestibulum et neque et, ullamcorper convallis lacus. Donec a neque iaculis,
            dictum nisl ut, dictum nisi. Praesent sagittis augue ac pulvinar lobortis. Quisque molestie velit metus,
            eu ultricies ligula accumsan tempus.
        </p>
        <p>
            Aliquam non enim in nulla pellentesque rhoncus. Aenean faucibus ligula quam, eu iaculis erat rhoncus vel.
            Maecenas non est et nisi accumsan faucibus vitae sit.
        </p>
        <blockquote class="flex gap-3 items-start border-l-0 my-10 pl-0 text-2xl font-normal not-italic text-slate-800
            before:content-[open-quote] before:-mt-2 before:text-blue-100 before:text-8xl before:leading-none before:font-bold">
            Nullam nec tortor semper, mattis tortor ut, dictum augue. Etiam vitae tellus turpis. Aenean dictum
            metus non turpis luctus, ut egestas mi facilisis.
        </blockquote>
        <p>
            Morbi in lectus at eros luctus mollis. Vivamus lobortis urna in quam dignissim tempus. Sed volutpat
            ipsum vitae justo sagittis venenatis. Vestibulum eros elit, scelerisque eget velit a, viverra eleifend
            augue. Integer in ante non felis ornare tempus. Nam ut mi id lorem maximus ornare sit amet vitae enim.
        </p>
        <p>
            Quisque accumsan congue ex in placerat. Donec ac pellentesque sapien, id ullamcorper nulla. Vestibulum
            tempus aliquam luctus. Nullam malesuada suscipit finibus. Sed posuere venenatis nisl, et vestibulum massa
            cursus vitae. Vivamus eu tempus mauris. Aliquam viverra mauris quam, maximus placerat arcu tristique sed.
            Nam at tincidunt lorem.
        </p>
    </div>
</article>
