<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductAttributes as ProductAttributes;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroiconsOutline */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Product $product */
if (! ($product = $block->getData('product'))) {
    return;
}

$productId = $product->getId();

/** @var ProductAttributes $productAttribute */
$productAttribute = $viewModels->require(ProductAttributes::class);
$productName = $productAttribute->getValue($product, 'name');

$classlist = $block->getData('class') ?: 'rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600';
?>
<button
    type="button"
    class="<?= $classlist ?>"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $productName) ?>"
    data-addto="wishlist"
    data-product-id="<?= (int) $productId ?>"
    x-data="initWishlist"
    x-defer="intersect"
    @click.prevent="addToWishlist"
>
    <?= $heroicons->heartHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
</button>
