<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

$showTitle = $block->getShowTitle() !== null ? $block->getShowTitle() : true;
$defaultWidth = 270;
$defaultHeight = 95;

$items = [
    [
        // Can also be a webp or jpg or any other image format
        'src' => $block->getViewFileUrl('Hyva_Theme::svg/lorum-logo-1.svg'),
        'alt' => 'Lorum Ipsum'
    ],
    [
        'src' => $block->getViewFileUrl('Hyva_Theme::svg/lorum-logo-2.svg'),
        'alt' => 'Lorum Ipsum'
    ],
    [
        'src' => $block->getViewFileUrl('Hyva_Theme::svg/lorum-logo-3.svg'),
        'alt' => 'Lorum Ipsum'
    ],
    [
        'src' => $block->getViewFileUrl('Hyva_Theme::svg/lorum-logo-4.svg'),
        'alt' => 'Lorum Ipsum'
    ],
    [
        'src' => $block->getViewFileUrl('Hyva_Theme::svg/lorum-logo-5.svg'),
        'alt' => 'Lorum Ipsum'
    ],
];

$marqueeClasses = "flex gap-[var(--gap)] select-none overflow-hidden mask-overflow border-y border-gray-300 py-10 md:py-7";
$marqueeGroupClasses = "shrink-0 flex gap-[var(--gap)] items-center justify-around min-w-full" .
    " animate-[marqueeScroll_var(--duration)_linear_infinite] motion-reduce:[animation-play-state:paused]";
?>

<section
    class="relative my-20"
    style="--size: clamp(10rem, 1rem + 40vmin, 30rem); --gap: calc(var(--size) / 14); --duration: 40s;"
    aria-label="<?= $escaper->escapeHtml(__('Our favorite brands')) ?>"
>
    <?php if ($showTitle): ?>
        <div class="mb-4 sm:flex sm:justify-between sm:items-baseline">
            <div class="text-3xl leading-9 font-bold text-gray-800">
                <?= $escaper->escapeHtml(__('Our favorite brands')) ?>
            </div>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="text-blue-700 text-lg leading-7 font-semibold"
            >
                <?= $escaper->escapeHtml(__('Browse all brands')) ?> →
            </a>
        </div>
    <?php endif; ?>

    <div class="<?= $escaper->escapeHtmlAttr($marqueeClasses) ?>">
        <div class="<?= $escaper->escapeHtmlAttr($marqueeGroupClasses) ?>">
            <?php foreach ($items as $item): ?>
                <img
                    src="<?= $escaper->escapeHtmlAttr($item['src']) ?>"
                    alt="<?= $escaper->escapeHtmlAttr($item['alt'] ?? '') ?>"
                    width="<?= $escaper->escapeHtmlAttr($item['width'] ?? $defaultWidth) ?>"
                    height="<?= $escaper->escapeHtmlAttr($item['height'] ?? $defaultHeight) ?>"
                    loading="lazy"
                >
            <?php endforeach; ?>
        </div>

        <?php // Fake row for CSS only marquee effect ?>
        <div aria-hidden="true" class="<?= $escaper->escapeHtmlAttr($marqueeGroupClasses) ?>">
            <?php foreach ($items as $item): ?>
                <img
                    src="<?= $escaper->escapeHtmlAttr($item['src']) ?>"
                    alt=""
                    width="<?= $escaper->escapeHtmlAttr($item['width'] ?? $defaultWidth) ?>"
                    height="<?= $escaper->escapeHtmlAttr($item['height'] ?? $defaultHeight) ?>"
                    loading="lazy"
                >
            <?php endforeach; ?>
        </div>
    </div>

    <style>
        @keyframes marqueeScroll {
            from {
                translate: none;
            }
            to {
                translate: calc(-100% - var(--gap));
            }
        }
    </style>
</section>
