<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

// This version of the mobile menu is only here to fix the issues found in the default theme version,
// This fixes the overlay (z-index) being present on the wrong element and the flex order classes only adding bad A11y with no layout benefit
// If you have your own version of a mobile menu feel free to replace it with this one
?>
<nav
    x-data="initMenuMobile"
    @load.window="setActiveMenu"
    @keydown.window.escape="closeMenu"
    class="navigation lg:hidden"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
    role="navigation"
>
    <!-- mobile -->
    <button
        x-ref="mobileMenuTrigger"
        @click="openMenu"
        :class="triggerButtonClass"
        type="button"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-haspopup="menu"
        :aria-expanded="open"
        :hidden="open"
    >
        <?= $heroicons->menuHtml('p-3', 48, 48, [":class" => "triggerSvgClass", "aria-hidden" => "true"]) ?>
    </button>
    <div
        x-ref="mobileMenuNavLinks"
        class="
            z-20 fixed top-0 right-0 w-full h-full p-1 hidden
            flex-col border-t border-container bg-container-lighter
            overflow-y-auto overflow-x-hidden
        "
        :class="mobileMenuNavLinksClass"
        :aria-hidden="closed"
        role="dialog"
        aria-modal="true"
    >
        <ul
            class="border-t flex flex-col gap-y-1 mt-16"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <li
                    data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>-main"
                    class="level-0"
                >
                    <div
                        class="flex items-center transition-transform duration-150 ease-in-out transform"
                        :class="level0TranslateClass"
                    >
                        <a
                            class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                bg-container-lighter border-container level-0
                            "
                            href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                            title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                        >
                            <?= $escaper->escapeHtml($menuItem['name']) ?>
                        </a>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <button
                                data-index="<?= $escaper->escapeHtmlAttr($index) ?>"
                                @click="openSubcategory"
                                class="absolute right-0 flex items-center justify-center w-11 h-11 mr-8 cursor-pointer
                                bg-container-lighter border-container"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $menuItem['name'])) ?>"
                                aria-haspopup="true"
                                :aria-expanded="mobilePanelActiveIdMatchesIndex"
                            >
                                <div class="w-8 h-8 border rounded">
                                    <?= $heroicons->chevronRightHtml('w-full h-full p-1', 24, 24, ["aria-hidden" => "true"]) ?>
                                </div>
                            </button>
                        <?php endif; ?>
                    </div>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <div
                            data-index="<?= $escaper->escapeHtmLAttr($index) ?>"
                            data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>"
                            class="absolute top-0 right-0 z-10 flex flex-col gap-1 w-full h-full p-1 bg-container-lighter"
                            :class="childMenuClass"
                        >
                            <ul
                                class="mt-16 transition-transform duration-200 ease-in-out translate-x-full transform"
                                data-index="<?= $escaper->escapeHtmLAttr($index) ?>"
                                :class="level1TranslateClass"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>"
                            >
                                <li>
                                    <button
                                        type="button"
                                        class="flex items-center px-8 py-4 border-b cursor-pointer bg-container border-container w-full border-t"
                                        data-index="'<?= $escaper->escapeHtmlAttr($index) ?>-main'"
                                        @click="backToMainCategories"
                                        aria-label="<?= $escaper->escapeHtmlAttr(__('Back to main categories')) ?>"
                                    >
                                        <?= $heroicons->chevronLeftHtml('', 24, 24, ["aria-hidden" => "true"]); ?>
                                        <span class="ml-4">
                                            <?= $escaper->escapeHtml($menuItem['name']) ?>
                                        </span>
                                    </button>
                                </li>
                                <li>
                                    <a
                                        href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                                        title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                                        class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                            bg-container-lighter border-container
                                        "
                                    >
                                        <span class="ml-10">
                                            <?= $escaper->escapeHtml(__('View All')) ?>
                                        </span>
                                    </a>
                                </li>
                                <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                    <li>
                                        <a
                                            href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                            title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                            class="flex items-center w-full px-8 py-4 border-b cursor-pointer
                                                bg-container-lighter border-container
                                            "
                                        >
                                            <span class="ml-10 text-base text-gray-700">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                            <button
                                @click="closeMenu"
                                class="absolute flex justify-end w-16 self-end mb-1 transition-none"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
                            >
                                <?= $heroicons->xHtml('hidden p-4', 64, 64, [":class" => "triggerCloseSvgClass", "aria-hidden" => "true"]) ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <button
            @click="closeMenu"
            class="absolute flex justify-end w-16 self-end mb-1"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
            type="button"
        >
            <?= $heroicons->xHtml('hidden p-4', 64, 64, [":class" => "triggerCloseSvgClass", "aria-hidden" => "true"]) ?>
        </button>
    </div>
</nav>
<script>
    const initMenuMobile = () => {
        return {
            mobilePanelActiveId: null,

            open: false,
            closed() {
                return !this.open
            },

            triggerButtonClass() {
                return {
                    'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full': this.open
                }
            },
            triggerSvgClass() {
                return {
                    'hidden': this.open,
                    'block': !this.open
                }
            },
            triggerCloseSvgClass() {
                return {
                    'hidden': !this.open,
                    'block': this.open
                }
            },
            mobileMenuNavLinksClass() {
                return {
                    'flex': this.open,
                    'hidden': !this.open
                }
            },
            level0TranslateClass() {
                return {
                    '-translate-x-full': this.mobilePanelActiveId,
                    'translate-x-0': !this.mobilePanelActiveId
                }
            },
            level1TranslateClass() {
                return {
                    'translate-x-full': !this.mobilePanelActiveIdMatchesIndex(),
                    'translate-x-0': this.mobilePanelActiveIdMatchesIndex(),
                }
            },
            childMenuClass() {
                return {
                    'hidden': !this.mobilePanelActiveIdMatchesIndex()
                }
            },

            mobilePanelActiveIdMatchesIndex() {
                return this.mobilePanelActiveId === this.$el.dataset.index
            },

            setActiveMenu() {
                const menuNode = this.$root

                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0]
                }).map(item => {
                    item.classList.add('underline')

                    item.closest('li.level-0') &&
                    item.closest('li.level-0').querySelector('a.level-0').classList.add('underline')
                })
            },
            openMenu() {
                this.open = true
                this.$nextTick(() => hyva.trapFocus(this.$refs['mobileMenuNavLinks']))
                // Prevent from body scrolling while mobile menu opened
                document.body.style.overflow = 'hidden'
            },
            closeMenu() {
                document.body.style.overflow = ''

                if (this.open) {
                    this.$nextTick(() => this.$refs['mobileMenuTrigger'].focus() || hyva.releaseFocus());
                }

                this.open = false
                this.mobilePanelActiveId = null
            },
            openSubcategory() {
                const
                    index = this.$el.dataset.index,
                    menuNodeRef = document.querySelector('[data-child-id=' + index + ']')

                this.mobilePanelActiveId = this.mobilePanelActiveId === index ? 0 : index
                this.$nextTick(() => hyva.trapFocus(menuNodeRef))
            },
            backToMainCategories() {
                const
                    index = this.$el.dataset.index,
                    menuNodeRef = document.querySelector('[data-child-id=' + index + ']')

                this.mobilePanelActiveId = 0
                this.$nextTick(() => {
                    hyva.trapFocus(this.$refs['mobileMenuNavLinks'])
                    menuNodeRef.querySelector('a').focus()
                })
            }
        }
    }

    window.addEventListener('alpine:init', () => Alpine.data('initMenuMobile', initMenuMobile), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
